import { executeInterCharge } from "../_shared/inter/charge-execution.ts";
import { jsonResponse, corsHeaders } from "../_shared/inter/http.ts";
import { readLimitedRequestText } from "../_shared/inter/validation.ts";
import { handleDraftAction } from "../fiscal-integration/draft-action.ts";
import type { FiscalRpcClient } from "../fiscal-integration/emission-action.ts";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const record = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const validId = (value: unknown): value is string => typeof value === "string" && UUID.test(value);
const FAILED = "A etapa da recorrencia nao foi confirmada. Os identificadores foram preservados; retome a mesma execucao para reconciliar.";

export interface WorkerOptions {
  productionEnabled?: boolean;
  authorize: (request: Request, executionId: string) => Promise<{ empresaId: string }>;
  charge?: typeof executeInterCharge;
  fiscal?: typeof handleDraftAction;
}

function trustedJob(value: unknown) {
  const job = record(value);
  if (![job.id, job.empresaId, job.userId, job.contratoId, job.leaseToken, job.requestId].every(validId)
    || !["cobranca", "rascunho", "fiscal"].includes(String(job.etapa))
    || !["sem_nfse", "rascunho", "na_data", "no_pagamento"].includes(String(job.modoFiscal))) {
    throw new Error("Execucao recorrente invalida.");
  }
  return job;
}

const summary = (job: Record<string, unknown>) => ({
  id: job.id, etapa: job.etapa, status: job.status,
  cobrancaId: job.cobrancaId || null, rascunhoId: job.rascunhoId || null, nfseId: job.nfseId || null,
});

/** The body only selects an execution. Tenant, actor, terms and IDs come from SQL. */
export async function handleRecurrenceWorker(req: Request, admin: FiscalRpcClient, options: WorkerOptions) {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders });
  if (req.method !== "POST") return jsonResponse({ ok: false, error: "Metodo nao permitido." }, 405);
  let body: Record<string, unknown>;
  try {
    if (!/^application\/json(?:\s*;|$)/i.test(req.headers.get("content-type") || "")) throw new Error();
    const parsed = JSON.parse(await readLimitedRequestText(req, 1024));
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error();
    body = record(parsed);
    if (Object.keys(body).some((key) => key !== "execucaoId")) throw new Error();
  } catch { return jsonResponse({ ok: false, error: "Requisicao invalida." }, 400); }

  let executionId: string | null = null;
  let tenant: string | undefined;
  const cronKey = req.headers.get("X-Arkhen-Recurrence-Key");
  const cron = cronKey !== null;
  if (cron) {
    if (body.execucaoId !== undefined) return jsonResponse({ ok: false, error: "Cron nao seleciona execucao." }, 400);
    if (!/^[0-9a-f]{64}$/.test(cronKey)) return jsonResponse({ ok: false, error: "Autorizacao invalida." }, 401);
    try {
      // A random, expiring capability generated by SQL cron is consumed once.
      // It is never accepted as a reusable service-role or user credential.
      const permit = await admin.rpc("consumir_capacidade_recorrencia", { p_token: cronKey });
      if (permit.error || permit.data !== true) throw new Error();
    } catch { return jsonResponse({ ok: false, error: "Autorizacao invalida." }, 401); }
  } else {
    if (!validId(body.execucaoId)) return jsonResponse({ ok: false, error: "Informe a execucao da recorrencia." }, 400);
    executionId = body.execucaoId;
    try {
      const auth = await options.authorize(req, executionId);
      if (!validId(auth.empresaId)) throw new Error();
      tenant = auth.empresaId;
    } catch { return jsonResponse({ ok: false, error: "Sem permissao para executar esta recorrencia." }, 403); }
  }

  const rpc = async (name: string, args: Record<string, unknown> = {}) => {
    const { data, error } = await admin.rpc(name, args);
    if (error) throw new Error(FAILED);
    return data;
  };
  let active: Record<string, unknown> | undefined;
  let last: Record<string, unknown> | undefined;
  let processed = 0;
  try {
    if (cron) await rpc("materializar_recorrencias_financeiras");
    // At most one cycle (three stages) per invocation. Every stage has a new SQL
    // lease; no-pagamento/review modes are blocked by the authoritative claim RPC.
    for (let stage = 0; stage < 3; stage++) {
      const claimed = await rpc("reivindicar_execucao_recorrencia", { p_execucao_id: executionId });
      if (!claimed) break;
      const candidate = trustedJob(claimed);
      if ((executionId && candidate.id !== executionId) || (tenant && candidate.empresaId !== tenant)) throw new Error(FAILED);
      active = candidate;
      executionId = active.id as string;
      const lease = { p_execucao_id: executionId, p_lease_token: active.leaseToken };
      let result: Record<string, unknown>;
      if (active.etapa === "cobranca") {
        const charge = record(await (options.charge || executeInterCharge)(admin, active.userId as string, {
          ...record(active.chargePayload), request_id: active.requestId,
        }));
        const chargeId = record(charge.cobranca).id;
        if (charge.ok !== true || !validId(chargeId)) throw new Error(FAILED);
        result = { etapa: "cobranca", cobrancaId: chargeId };
      } else if (active.etapa === "rascunho") {
        const draft = record(await rpc("preparar_rascunho_recorrencia", lease));
        if (!validId(draft.rascunhoId)) throw new Error(FAILED);
        result = { etapa: "rascunho", rascunhoId: draft.rascunhoId };
      } else {
        if (!validId(active.rascunhoId) || !["na_data", "no_pagamento"].includes(String(active.modoFiscal))
          || !["producao", "homologacao"].includes(String(active.ambiente))) throw new Error(FAILED);
        const fiscal = record(await (options.fiscal || handleDraftAction)(admin, active.userId as string,
          active.rascunhoId, false, options.productionEnabled === true));
        if (fiscal.ok !== true || !fiscal.nfseId || (fiscal.situacao && fiscal.situacao !== "confirmada")) throw new Error(FAILED);
        result = { etapa: "fiscal", nfseId: fiscal.nfseId };
      }
      last = record(await rpc("finalizar_etapa_recorrencia", { ...lease, p_resultado: result }));
      if (last.id !== executionId) throw new Error(FAILED);
      active = undefined;
      processed++;
      if (last.etapa === "concluida" || ["concluida", "aguardando_revisao", "aguardando_pagamento"].includes(String(last.status))) break;
    }
    return jsonResponse({ ok: true, processed, ...(last ? { execucao: summary(last) } : {}),
      ...(!cron && processed === 0 ? { pending: true,
        message: "Nenhuma etapa disponivel agora. Consulte a situacao no historico: a execucao pode aguardar pagamento, data de processamento, revisao ou outra tentativa em andamento." } : {}),
    });
  } catch {
    if (active && validId(active.id) && validId(active.leaseToken)) {
      await Promise.resolve(admin.rpc("falhar_execucao_recorrencia", {
        p_execucao_id: active.id, p_lease_token: active.leaseToken, p_mensagem: FAILED,
      })).catch(() => {});
    }
    return jsonResponse({ ok: false, processed, execucaoId: executionId, error: FAILED }, 200);
  }
}
