export const TAB_INFOS: Record<string, { title: string; iconName: string }> = {
  inicio: { title: 'Início', iconName: 'LayoutDashboard' },
  clientes: { title: 'Clientes', iconName: 'Building2' },
  'parametrizacao-regimes': { title: 'Regimes Tributários', iconName: 'Database' },
  'parametrizacao-tipos-empresa': { title: 'Tipos de Empresa', iconName: 'Database' },
  'parametrizacao-natureza-juridica': { title: 'Natureza Jurídica', iconName: 'Database' },
  'parametrizacao-tipos-parceiros': { title: 'Tipos de Parceiros', iconName: 'Database' },
  'parametrizacao-categorias-clientes': { title: 'Categorias de Clientes', iconName: 'Database' },
  'parametrizacao-cnae': { title: 'CNAE', iconName: 'Database' },
  'parametrizacao-regras': { title: 'Impostos', iconName: 'Database' },
  'parametrizacao-documentos': { title: 'Tipos de Documentos', iconName: 'Database' },
  'parametrizacao-parametros-calculo': { title: 'Parâmetros de Cálculo', iconName: 'Database' },
  'parametrizacao-prazos-entrega': { title: 'Obrigações', iconName: 'Database' },
  'parametrizacao-protocolos': { title: 'Catálogo de Obrigações', iconName: 'Database' },
  'parametrizacao-checklists': { title: 'Modelos de Checklists', iconName: 'ClipboardList' },
  atividades: { title: 'Atividades', iconName: 'ClipboardList' },
  'atividades-diarias': { title: 'Atividades diárias', iconName: 'Clock' },
  'atividades-semanais': { title: 'Atividades semanais', iconName: 'CalendarDays' },
  'atividades-mensais': { title: 'Atividades mensais', iconName: 'Calendar' },
  'atividades-empresa': { title: 'Atividades por empresa', iconName: 'Building2' },
  'atividades-funcionario': { title: 'Atividades por funcionário', iconName: 'User' },
  'atividades-internas': { title: 'Atividades internas', iconName: 'ListChecks' },
  'atividades-rotinas': { title: 'Checklists', iconName: 'Repeat' },
  'atividades-controle': { title: 'Controle de andamento', iconName: 'Layers' },
  'gestao-empresarial': { title: 'Gestão Empresarial', iconName: 'Briefcase' },
  'planejamento-tributario': { title: 'Planejamento Tributário', iconName: 'Percent' },
  'simulacoes-calculos': { title: 'Simulações e Cálculos', iconName: 'Calculator' },
  agenda: { title: 'Agenda', iconName: 'CalendarDays' },
  conformidade: { title: 'Conformidade', iconName: 'ShieldCheck' },
  protocolos: { title: 'Protocolo e Obrigações', iconName: 'FileCheck' },
  documentos: { title: 'Documentos', iconName: 'FolderOpen' },
  faturamento: { title: 'Faturamento', iconName: 'Receipt' },
  financeiro: { title: 'Financeiro', iconName: 'Landmark' },
  relatorios: { title: 'Relatórios', iconName: 'BarChart3' },
  configuracoes: { title: 'Configurações', iconName: 'Settings' },
};
