export const TAB_INFOS: Record<string, { title: string; iconName: string }> = {
  inicio: { title: 'Início', iconName: 'LayoutDashboard' },
  clientes: { title: 'Clientes', iconName: 'Building2' },
  'parametrizacao-regimes': { title: 'Regimes Tributários', iconName: 'Database' },
  'parametrizacao-tipos-empresa': { title: 'Tipos de Empresa', iconName: 'Database' },
  'parametrizacao-natureza-juridica': { title: 'Natureza Jurídica', iconName: 'Database' },
  'parametrizacao-tipos-parceiros': { title: 'Tipos de Parceiros', iconName: 'Database' },
  'parametrizacao-categorias-clientes': { title: 'Categorias de Clientes', iconName: 'Database' },
  'parametrizacao-cnae': { title: 'CNAE', iconName: 'Database' },
  'parametrizacao-regras': { title: 'Impostos', iconName: 'Database' },
  'parametrizacao-documentos': { title: 'Tipos de Documentos', iconName: 'Database' },
  'parametrizacao-pastas-padrao': { title: 'Pastas Padrão', iconName: 'FolderTree' },
  'parametrizacao-parametros-calculo': { title: 'Parâmetros de Cálculo', iconName: 'Database' },
  'parametrizacao-tabelas-tributarias': { title: 'Tabelas Tributárias', iconName: 'Database' },
  'parametrizacao-prazos-entrega': { title: 'Obrigações', iconName: 'Database' },
  'parametrizacao-protocolos': { title: 'Catálogo de Obrigações', iconName: 'Database' },
  'parametrizacao-checklists': { title: 'Modelos de Checklists', iconName: 'ClipboardList' },
  'parametrizacao-categoria-financeira': { title: 'Categorias Financeiras', iconName: 'Database' },
  atividades: { title: 'Minha Fila', iconName: 'ClipboardList' },
  'atividades-equipe': { title: 'Equipe', iconName: 'User' },
  'atividades-fechamentos': { title: 'Fechamentos de Clientes', iconName: 'Building2' },
  'atividades-modelos': { title: 'Rotinas e Modelos', iconName: 'Repeat' },
  'atividades-painel-operacional': { title: 'Painel Operacional', iconName: 'Layers' },
  'atividades-diarias': { title: 'Minha Fila / Hoje', iconName: 'Clock' },
  'atividades-semanais': { title: 'Minha Fila / Semana', iconName: 'CalendarDays' },
  'atividades-mensais': { title: 'Minha Fila / Mês', iconName: 'Calendar' },
  'atividades-empresa': { title: 'Fechamentos de Clientes', iconName: 'Building2' },
  'atividades-funcionario': { title: 'Equipe', iconName: 'User' },
  'atividades-internas': { title: 'Minha Fila / Internas', iconName: 'ListChecks' },
  'atividades-rotinas': { title: 'Rotinas e Modelos', iconName: 'Repeat' },
  'atividades-controle': { title: 'Painel Operacional', iconName: 'Layers' },
  'gestao-empresarial': { title: 'Gestão Empresarial', iconName: 'Briefcase' },
  'planejamento-tributario': { title: 'Planejamento Tributário', iconName: 'Percent' },
  'simulacoes-calculos': { title: 'Simulações e Cálculos', iconName: 'Calculator' },
  'reforma-tributaria': { title: 'Reforma Tributária', iconName: 'Scale' },
  agenda: { title: 'Agenda', iconName: 'CalendarDays' },
  conformidade: { title: 'Conformidade', iconName: 'ShieldCheck' },
  protocolos: { title: 'Protocolos e Documentos', iconName: 'FileCheck' },
  documentos: { title: 'Documentos', iconName: 'FolderOpen' },
  faturamento: { title: 'Faturamento', iconName: 'Receipt' },
  financeiro: { title: 'Financeiro', iconName: 'Landmark' },
  relatorios: { title: 'Relatórios', iconName: 'BarChart3' },
  configuracoes: { title: 'Configurações', iconName: 'Settings' },
  'guia-ajuda': { title: 'Guia de Navegação', iconName: 'Headphones' },
};
