export const configuracoesKeys = {
  all: ['configuracoes'] as const,
  empresa: () => [...configuracoesKeys.all, 'empresa'] as const,
  marcaDagua: () => [...configuracoesKeys.all, 'marca-dagua'] as const,
  perfisAcesso: () => [...configuracoesKeys.all, 'perfis-acesso'] as const,
  usuarios: () => [...configuracoesKeys.all, 'usuarios'] as const,
  xmlModelos: () => [...configuracoesKeys.all, 'xml-modelos'] as const,
  contasBancarias: () => [...configuracoesKeys.all, 'contas-bancarias'] as const,
  contasBancariasResumo: () => [...configuracoesKeys.contasBancarias(), 'resumo'] as const,
  contadores: () => [...configuracoesKeys.all, 'contadores'] as const,
  logsEventos: () => [...configuracoesKeys.all, 'logs-eventos'] as const,
  integracaoBancaria: () => [...configuracoesKeys.all, 'integracao-bancaria'] as const,
  asaas: () => [...configuracoesKeys.integracaoBancaria(), 'asaas'] as const,
  inter: () => [...configuracoesKeys.integracaoBancaria(), 'inter'] as const,
  modulosSistema: () => [...configuracoesKeys.all, 'modulos-sistema'] as const,
};
