import type { GuideModule } from '../types';

export const CONFIGURACOES_GUIDE: GuideModule = {
  id: 'configuracoes', title: 'Configurações', icon: 'Settings',
  description: 'Prepare o escritório, cadastre a equipe, organize acessos e configure contas e documentos.',
  articles: [
    {
      id: 'configuracoes-empresa', title: 'Conferir os dados do escritório',
      summary: 'Mantenha identificação e contatos da empresa que opera o sistema.', path: 'Configurações → Dados da Empresa',
      prerequisites: ['Acesso ao cadastro do escritório e dados atualizados da empresa.'],
      steps: [
        { title: 'Abra a configuração', description: 'Acesse Configurações e escolha Dados da Empresa. Este cadastro identifica o escritório que utiliza o sistema.' },
        { title: 'Confira a identificação', description: 'Revise CNPJ da Empresa, Inscrição Estadual, Razão Social e Nome Fantasia.' },
        { title: 'Atualize contato e endereço', description: 'Preencha E-mail Corporativo, Telefone, CEP, Endereço / Logradouro, Nº, Cidade e Estado.' },
        { title: 'Salve os dados', description: 'Clique em Salvar Alterações. Aguarde a confirmação e reabra o cadastro para conferir as informações.' },
      ], verification: ['Os dados persistem após reabrir a configuração.'],
      tips: ['Os clientes e fornecedores são cadastrados em Parceiros. Confira qual empresa está editando antes de salvar.'],
    },
    {
      id: 'configuracoes-perfil-pessoal', title: 'Atualizar meu perfil e minhas preferências',
      summary: 'Edite seus dados pessoais, foto e comportamento das ferramentas.', path: 'Configurações → Meu Perfil / Modelo da Calculadora',
      prerequisites: ['Sessão autenticada com sua própria conta.'],
      steps: [
        { title: 'Confira sua identidade', description: 'Abra Meu Perfil e confira Nome Completo, E-mail corporativo, CPF e Data de nascimento.' },
        { title: 'Atualize os campos disponíveis', description: 'Edite os dados permitidos e clique em Salvar Cadastro. No acesso por CPF, nome e CPF podem estar bloqueados para edição.' },
        { title: 'Atualize a foto', description: 'Use a ação de enviar nova foto e selecione sua imagem. Aguarde a atualização da prévia.' },
        { title: 'Defina preferências', description: 'Volte para Configurações, abra Modelo da Calculadora e escolha Modelo Padrão da Calculadora e Comportamento de Abas Internas. Clique em Salvar Preferências.' },
      ], verification: ['Seu perfil mostra os dados e a foto salvos.', 'As preferências selecionadas aparecem ao reabrir a configuração.'],
      tips: ['As opções de senha e conta Google dependem da forma de acesso apresentada no seu perfil. Siga as instruções da própria seção.'],
    },
    {
      id: 'configuracoes-usuario-email', title: 'Cadastrar um usuário com convite por e-mail',
      summary: 'Convide um integrante para criar a própria senha e acessar o escritório.', path: 'Configurações → Gestão de Usuários → Novo Usuário',
      prerequisites: ['Permissão de gestão de usuários.', 'E-mail do integrante e perfil de acesso definido.'],
      steps: [
        { title: 'Abra Novo Usuário', description: 'Em Gestão de Usuários, clique em Novo Usuário e escolha a forma de acesso E-mail.' },
        { title: 'Informe a identidade', description: 'Preencha Nome Completo, E-mail, CPF e Telefone conforme os campos exigidos no formulário.' },
        { title: 'Defina o acesso', description: 'Escolha Perfil de Acesso e confira Status. Se a rotina exigir restrição de horário, configure Dias permitidos, Intervalos permitidos e a mensagem fora do período.' },
        { title: 'Salve o convite', description: 'Clique em Salvar Usuário. O usuário fica pendente até aceitar o convite; confira a seção Convite por e-mail no cartão.' },
        { title: 'Oriente o primeiro acesso', description: 'O integrante deve abrir o link recebido no próprio e-mail e criar sua senha. Se necessário, use Enviar convite ou Reenviar convite no cartão e confira o retorno.' },
      ], verification: ['O cartão apresenta e-mail, perfil e status corretos.', 'O status do convite permite acompanhar o aceite; cadastro pendente não equivale a acesso concluído.'],
      related: ['configuracoes-perfis', 'configuracoes-usuario-edicao'],
    },
    {
      id: 'configuracoes-usuario-cpf', title: 'Cadastrar acesso por CPF e concluir o primeiro login',
      summary: 'Crie acesso com senha temporária e acompanhe a troca obrigatória no primeiro login.', path: 'Configurações → Gestão de Usuários → Novo Usuário → Somente CPF',
      prerequisites: ['Permissão de gestão de usuários.', 'Nome e CPF corretos do integrante.'],
      steps: [
        { title: 'Escolha o acesso por CPF', description: 'Abra Novo Usuário e selecione Somente CPF. E-mail de contato e telefone são opcionais nessa modalidade.' },
        { title: 'Defina identidade e perfil', description: 'Preencha Nome Completo, CPF e Perfil de Acesso. Confira as regras de dias e horários, quando usadas pelo escritório.' },
        { title: 'Crie o acesso', description: 'Clique em Salvar Usuário e aguarde a janela Senha temporária criada.' },
        { title: 'Entregue a senha ao titular', description: 'Disponibilize a senha temporária ao próprio integrante por um canal apropriado. Ao fechar a janela, a senha temporária é apagada da exibição.' },
        { title: 'Conclua o primeiro acesso', description: 'O integrante deve entrar com CPF e senha temporária e realizar a troca de senha exigida. Confira no cartão se ainda aparece Primeiro acesso pendente.' },
      ], verification: ['O cartão apresenta Forma de acesso: CPF + senha.', 'A indicação de primeiro acesso pendente é resolvida após o titular concluir a troca obrigatória.'],
      tips: ['Não inclua senhas em observações, documentos compartilhados ou imagens do manual.'],
    },
    {
      id: 'configuracoes-usuario-edicao', title: 'Editar acesso, inativar ou redefinir senha',
      summary: 'Mantenha perfil, horários e status da equipe atualizados.', path: 'Configurações → Gestão de Usuários',
      prerequisites: ['Permissão de gestão de usuários.', 'Usuário correto identificado pelo nome e CPF ou e-mail.'],
      steps: [
        { title: 'Abra o integrante', description: 'Localize o cartão e confira nome, perfil, forma de acesso e status antes de escolher Editar.' },
        { title: 'Atualize as regras', description: 'Ajuste os campos permitidos, Perfil de Acesso, Status e restrições de horários. Clique em Salvar Usuário.' },
        { title: 'Interrompa acesso quando necessário', description: 'Use Inativar para um integrante que não deve mais acessar. Confira o status Inativo no cartão após a ação.' },
        { title: 'Resolva acesso por CPF', description: 'Quando disponível para a conta CPF, clique em Redefinir senha. Preencha Nova senha e Confirmar nova senha e use Salvar nova senha.' },
        { title: 'Trate um cadastro sem conta', description: 'Excluir cadastro aparece apenas para registros sem conta de acesso vinculada. Leia a confirmação antes de concluir a exclusão.' },
      ], verification: ['O cartão reflete o perfil, status e horários definidos.', 'O convite de e-mail é tratado pela seção própria quando ainda estiver pendente.'],
    },
    {
      id: 'configuracoes-perfis', title: 'Criar perfis e distribuir permissões',
      summary: 'Organize quais recursos cada função da equipe pode utilizar.', path: 'Configurações → Perfis de Acesso / Permissões do Sistema',
      prerequisites: ['Permissão para gerenciar perfis.', 'Lista de atividades que cada função precisa executar.'],
      steps: [
        { title: 'Consulte os perfis', description: 'Abra Perfis de Acesso e confira os perfis existentes. Abra a criação de perfil ou use Editar perfil em um cartão.' },
        { title: 'Identifique a função', description: 'Preencha Nome do perfil e Descrição operacional para explicar a responsabilidade dessa função.' },
        { title: 'Selecione recursos', description: 'Marque as Permissões ativas necessárias e clique em Salvar Perfil. Use Permissões do Sistema para consultar e gerenciar os privilégios por perfil.' },
        { title: 'Vincule à equipe', description: 'Em Gestão de Usuários, edite o integrante, selecione o Perfil de Acesso desejado e salve.' },
        { title: 'Confira a configuração', description: 'Reabra o perfil e confira as permissões salvas; no cartão do integrante, confirme o perfil associado.' },
      ], verification: ['Perfil e permissões correspondem às atividades do integrante.'],
      tips: ['Um recurso pode não aparecer porque o usuário não tem permissão ou porque o módulo está desativado para o escritório.', 'Inativar perfil é uma ação diferente de inativar um usuário; leia as condições apresentadas pela confirmação.'],
    },
    {
      id: 'configuracoes-modulos', title: 'Ativar módulos para a equipe',
      summary: 'Defina quais funcionalidades ficam disponíveis no escritório.', path: 'Configurações → Módulos do Sistema',
      prerequisites: ['Permissão para gerenciar configurações do escritório.'],
      steps: [
        { title: 'Abra o catálogo', description: 'Em Configurações, selecione Módulos do Sistema e confira os módulos disponíveis.' },
        { title: 'Revise o uso da equipe', description: 'Identifique quais módulos são necessários na rotina do escritório antes de alterar sua disponibilidade.' },
        { title: 'Ajuste as opções', description: 'Ative ou desative os módulos permitidos. Módulos obrigatórios apresentam a opção bloqueada.' },
        { title: 'Salve e confira', description: 'Clique em Salvar módulos. Confira as opções gravadas e a disponibilidade dos módulos no menu.' },
      ], verification: ['O estado dos módulos permanece após reabrir a configuração.'],
      tips: ['Ativar um módulo não concede automaticamente todas as permissões aos usuários. Confira também Perfis de Acesso.'],
    },
    {
      id: 'configuracoes-contadores', title: 'Cadastrar o contador responsável',
      summary: 'Registre os profissionais do escritório e escolha o responsável técnico.', path: 'Configurações → Contadores Responsáveis',
      prerequisites: ['Nome, CRC, CPF/CNPJ e e-mail do contador conferidos.'],
      steps: [
        { title: 'Abra a lista', description: 'Selecione Contadores Responsáveis e clique em Cadastrar Contador.' },
        { title: 'Preencha o cadastro', description: 'Informe os dados do profissional no formulário Cadastrar Novo Contador, incluindo CRC e CPF/CNPJ usados na identificação.' },
        { title: 'Confirme o cadastro', description: 'Envie o formulário e localize o profissional na tabela Gestão de Contadores.' },
        { title: 'Defina o responsável', description: 'Na coluna Ações, use Definir como Responsável Técnico no contador escolhido e confira a indicação Responsável Técnico.' },
      ], verification: ['Nome, CRC e documento estão corretos na tabela.', 'O profissional escolhido aparece como responsável técnico.'],
      tips: ['Esse cadastro identifica o responsável nos fluxos que o utilizam; não representa por si só uma assinatura digital de documento.'],
    },
    {
      id: 'configuracoes-contas', title: 'Cadastrar e editar contas bancárias',
      summary: 'Prepare as contas usadas em recebimentos, pagamentos e transferências internas.', path: 'Configurações → Contas Bancárias',
      prerequisites: ['Banco, agência, número da conta e saldo inicial conferidos.'],
      steps: [
        { title: 'Abra o cadastro', description: 'Selecione Contas Bancárias e abra Adicionar Conta Bancária pela ação de inclusão.' },
        { title: 'Informe a conta', description: 'Preencha Instituição Financeira (Banco), Agência, Conta Corrente e Tipo de Conta.' },
        { title: 'Confira o saldo inicial', description: 'Informe Saldo Inicial (R$) com base no início do controle dessa conta e clique em Confirmar.' },
        { title: 'Edite quando necessário', description: 'Localize a conta em Contas Cadastradas, use Editar Conta, ajuste os dados e confirme.' },
        { title: 'Confira o uso financeiro', description: 'Abra Financeiro → Caixa e confira Saldos das Contas. A conta deve estar disponível nos seletores de entradas e saídas aplicáveis.' },
      ], verification: ['A conta aparece com banco, agência e número corretos.'],
      tips: ['Cadastrar a conta não conecta automaticamente a API do banco. A integração é configurada em Integrações Bancárias.', 'Remover Conta abre uma confirmação; confira o histórico de uso antes de excluir.'],
    },
    {
      id: 'configuracoes-bancaria', title: 'Preparar a integração bancária',
      summary: 'Entenda onde configurar o Banco Inter e conferir sua disponibilidade para cobranças.', path: 'Configurações → Integrações Bancárias → Configurar',
      prerequisites: ['Permissão de integração bancária.', 'Credenciais e certificados da integração fornecidos pelo responsável da conta.'],
      steps: [
        { title: 'Abra o banco', description: 'Em Integrações Bancárias, confira o catálogo e use Configurar no Banco Inter.' },
        { title: 'Confira o ambiente', description: 'Selecione o ambiente permitido e leia as orientações exibidas. Homologação e Produção têm contextos distintos; não troque de ambiente sem conferir os dados.' },
        { title: 'Preencha as seções', description: 'Revise Credenciais, Boleto, Pix e Webhook com os dados da integração autorizada pelo escritório.' },
        { title: 'Salve e valide', description: 'Use Salvar Banco Inter e a ação de testar conexão disponível. Leia o retorno para identificar pendências de credenciais, certificado ou permissões.' },
        { title: 'Confira o banco padrão', description: 'Volte ao catálogo e confira o status. Usar como padrão só fica disponível quando a integração atende às condições de configuração.' },
      ], verification: ['O retorno da conexão foi conferido e o catálogo apresenta a situação real da configuração.'],
      tips: ['A existência de uma conta cadastrada não comprova que a integração está válida. Confira o resultado da conexão antes de gerar cobranças.'],
    },
    {
      id: 'configuracoes-fiscal', title: 'Conferir a preparação da integração fiscal',
      summary: 'Localize contexto, certificado e parâmetros que antecedem a preparação de NFS-e.', path: 'Configurações → Integração Fiscal (NFS-e)',
      prerequisites: ['Permissão de integração fiscal.', 'Dados do emitente e configuração orientados pelo responsável fiscal.'],
      steps: [
        { title: 'Confira a configuração', description: 'Abra Integração Fiscal (NFS-e) e identifique o emitente, município e ambiente que serão utilizados.' },
        { title: 'Revise o contexto municipal', description: 'Confira o cadastro da localidade e do contribuinte. A disponibilidade de uma localidade no cadastro não comprova que todas as operações estejam integradas.' },
        { title: 'Confira certificado e RPS', description: 'Revise o certificado A1, sua validade e os parâmetros do RPS nas seções correspondentes.' },
        { title: 'Salve e leia o resumo', description: 'Use Salvar Configurações e consulte os pré-requisitos do resumo. Execute os testes de conexão e assinatura disponibilizados pela configuração quando necessário.' },
        { title: 'Prepare o documento', description: 'Com as pendências resolvidas, use Faturamento para preparar e revisar o rascunho. Confira o contexto novamente no formulário da nota.' },
      ], verification: ['Emitente, ambiente, certificado e parâmetros pertencem à configuração desejada.', 'Os testes e pré-requisitos não apresentam pendências não tratadas.'],
      tips: ['Salvar configurações e testar conexão não emitem uma nota.', 'Habilitação municipal e suporte do provedor são pré-requisitos externos; o cadastro no sistema não os substitui.'],
      related: ['faturamento-nfse-rascunho'],
    },
    {
      id: 'configuracoes-documentos', title: 'Configurar marca d’água e modelos XML',
      summary: 'Ajuste a apresentação de relatórios e a leitura de documentos fiscais.', path: 'Configurações → Marca d’Água / Modelos de XML',
      prerequisites: ['Permissão de gestão de documentos ou integração fiscal, conforme a configuração.', 'Logotipos e XML de exemplo adequados ao modelo.'],
      steps: [
        { title: 'Abra a marca d’água', description: 'Em Marca d’Água, confira a ativação e os logotipos Paisagem (Horizontal) e Retrato (Vertical).' },
        { title: 'Ajuste a aparência', description: 'Escolha Posição da Marca, Opacidade e Tamanho para a orientação selecionada. Confira a prévia e salve pelo botão da configuração.' },
        { title: 'Abra os modelos XML', description: 'Volte a Configurações e abra Modelos de XML. Escolha o tipo de documento e o estado Autorizado ou Cancelado.' },
        { title: 'Edite o modelo', description: 'Confira Título do modelo, Descrição, Arquivo XML de exemplo, Campos exibidos e Modelo textual. Revise a prévia e clique em Salvar modelos.' },
        { title: 'Confira o documento final', description: 'Gere a prévia de um documento que utiliza essa configuração e confira identificação, legibilidade e posição da marca.' },
      ], verification: ['A configuração salva permanece ao reabrir a tela.', 'A prévia do documento fica legível e apresenta o modelo esperado.'],
      tips: ['Alterar o modelo de visualização não modifica o conteúdo fiscal do XML original.', 'O alcance da marca d’água depende dos geradores que usam essa configuração.'],
    },
    {
      id: 'configuracoes-compartilhamento', title: 'Configurar e revisar compartilhamentos externos',
      summary: 'Mantenha padrões de expiração e acompanhe os links de documentos existentes.', path: 'Configurações → Compartilhamento de Docs',
      prerequisites: ['Permissão de gestão de documentos.'],
      steps: [
        { title: 'Revise os padrões', description: 'Abra Compartilhamento de Docs e confira as opções de proteção e Tempo de expiração padrão.' },
        { title: 'Salve a configuração', description: 'Ajuste as opções de acordo com a rotina do escritório e clique em Salvar Configurações.' },
        { title: 'Localize um compartilhamento', description: 'Na lista de links, busque por documento ou empresa. Confira documento, destino e status antes de copiar a URL.' },
        { title: 'Encerre acessos que não serão mais usados', description: 'Use Revogar link no compartilhamento correto e leia a confirmação Revogar Compartilhamento antes de concluir.' },
      ], verification: ['O link selecionado corresponde ao documento pretendido.', 'Após revogação, confira a atualização do status na lista.'],
      tips: ['Um link expirado não deve ser tratado como compartilhamento ativo. Confira a disponibilidade antes de enviá-lo.'],
    },
    {
      id: 'configuracoes-auditoria', title: 'Consultar eventos e entender Status das APIs',
      summary: 'Localize registros de ações e conheça o limite do painel de disponibilidade.', path: 'Configurações → Logs e Eventos / Status das APIs',
      prerequisites: ['Permissão de gestão de configurações.'],
      steps: [
        { title: 'Abra os eventos', description: 'Selecione Logs e Eventos para consultar Logs de Auditoria e Eventos.' },
        { title: 'Localize uma ação', description: 'Use Buscar por usuário ou ação e confira módulo, tipo, horário e informações apresentadas na linha.' },
        { title: 'Confronte o resultado', description: 'Abra o registro correspondente no módulo de origem para conferir seu estado atual. A lista de eventos traz os registros recentes disponíveis.' },
        { title: 'Interprete o painel de APIs', description: 'Em Status das APIs, os cartões exibem nome, status, latência e uptime. Nesta versão esses indicadores são demonstrativos, com valores fixos.' },
      ], verification: ['A ação foi identificada no histórico e conferida no módulo de origem.'],
      tips: ['Status das APIs ainda não faz monitoramento ao vivo. Use o teste real da integração e o retorno da operação para diagnosticar uma conexão.'],
    },
  ],
};
