import type { GuideModule } from '../types';

export const FATURAMENTO_FINANCEIRO_GUIDE: GuideModule[] = [
  {
    id: 'faturamento', title: 'Faturamento', icon: 'Receipt',
    description: 'Crie cobranças, organize mensalidades e prepare documentos fiscais com conferência em cada etapa.',
    articles: [
      {
        id: 'faturamento-cobranca', title: 'Criar uma cobrança avulsa',
        summary: 'Gere uma cobrança para um serviço pontual e localize o documento de pagamento.',
        path: 'Faturamento → Novo Lançamento → Apenas cobrança',
        prerequisites: ['Parceiro cadastrado com dados de identificação e endereço conferidos.', 'Integração bancária configurada pelo responsável do escritório.'],
        steps: [
          { title: 'Escolha o lançamento', description: 'Abra Novo Lançamento, selecione Apenas cobrança e clique em Continuar.' },
          { title: 'Identifique a cobrança', description: 'Pesquise o Parceiro / Cliente por nome ou CPF/CNPJ. Preencha Valor (R$), Data de vencimento e Descrição com o serviço e o período correspondente.' },
          { title: 'Defina o pagamento', description: 'Selecione a Forma de Pagamento. Confira desconto, juros, multa e Mensagem no boleto conforme as condições combinadas.' },
          { title: 'Confira e gere', description: 'Revise cliente, valor e vencimento antes de Confirmar Geração. Esta ação cria a cobrança na integração bancária configurada.' },
          { title: 'Localize o resultado', description: 'Confira o resumo e o Link da página de cobrança. Use Abrir cobrança ou Abrir boleto Inter quando disponíveis; depois clique em Concluir.' },
        ],
        verification: ['A cobrança aparece em Faturamento → Financeiro e em Financeiro → Contas a Receber.', 'O resumo mostra o parceiro, o valor e o vencimento que você conferiu.'],
        tips: ['Se o banco ainda estiver processando o documento, consulte o registro existente antes de criar outra cobrança.', 'Copiar link e Copiar mensagem ajudam a preparar o envio ao cliente; confira o destinatário ao compartilhar.'],
        related: ['faturamento-recorrencias', 'financeiro-receber'],
      },
      {
        id: 'faturamento-recorrencias', title: 'Cadastrar e programar mensalidades recorrentes',
        summary: 'Salve o contrato, escolha a primeira competência e defina como as próximas mensalidades serão processadas.',
        path: 'Faturamento → Recorrências → Nova recorrência',
        prerequisites: ['Parceiro, valor mensal e condições de pagamento conferidos.', 'Permissão de gestão financeira e integração bancária pronta para gerar cobranças.', 'Para incluir NFS-e, configuração do escritório e dados fiscais revisados.'],
        steps: [
          { title: 'Identifique o contrato', description: 'Abra Nova recorrência. Selecione Parceiro / Cliente, Valor mensal, Dia de vencimento e Descrição da cobrança. Você pode usar [MES] e [ANO] para identificar a competência na descrição.' },
          { title: 'Salve as condições de pagamento', description: 'Confira Forma de pagamento, desconto, juros, multa e Mensagem do boleto. Essas condições ficam registradas no contrato para as competências futuras.' },
          { title: 'Defina a competência', description: 'Em Competência e próximas mensalidades, preencha Primeira competência, Dia de processamento e Competência da mensalidade. Escolha Mês do processamento ou Mês anterior ao processamento; o vencimento é uma data distinta.' },
          { title: 'Escolha quando começar', description: 'Gerar primeira cobrança automaticamente processa a primeira competência após salvar. Ativar agendamento mensal autoriza as próximas competências nas condições do contrato. Confira as duas opções separadamente; o agendamento começa desmarcado.' },
          { title: 'Escolha o tratamento fiscal', description: 'O padrão da nova recorrência é Somente cobrança; preparar nota separadamente. Para conferir antes de transmitir, escolha Gerar rascunho para revisar antes de transmitir. As opções de transmissão na data ou após pagamento exigem configuração fiscal e autorização no ambiente selecionado.' },
          { title: 'Confira e salve', description: 'Se escolheu NFS-e, revise Ambiente fiscal, Emitente da NFS-e e os campos fiscais. Clique em Salvar Recorrência. Acompanhe o resultado em Execuções por competência, mesmo que a cobrança ainda esteja em processamento.' },
        ],
        verification: ['O contrato aparece com parceiro, valor, vencimento e condições corretos.', 'A primeira competência e o estado do agendamento estão corretos.', 'A cobrança ou o rascunho gerado é conferido na tela correspondente; salvar o contrato não comprova emissão de NFS-e.'],
        tips: ['Produção depende de liberação fiscal; selecionar esse ambiente não libera a transmissão. Homologação não tem valor fiscal.', 'Contratos antigos não são ativados automaticamente: abra Configurações da Recorrência e revise as condições.', 'Se uma etapa falhar, retome a mesma execução. Não cadastre outro contrato para tentar gerar a mesma mensalidade.'],
        related: ['faturamento-recorrencia-configurar', 'faturamento-recorrencia-execucoes', 'faturamento-nfse-rascunho'],
      },
      {
        id: 'faturamento-recorrencia-configurar', title: 'Editar ou pausar uma recorrência',
        summary: 'Atualize condições para competências futuras e controle o agendamento mensal.',
        path: 'Faturamento → Recorrências → abrir contrato → Configurações da Recorrência',
        prerequisites: ['Contrato existente e permissão para gerenciar faturamento ou financeiro.'],
        steps: [
          { title: 'Abra o contrato correto', description: 'Na lista de Recorrências, abra o parceiro desejado e selecione Configurações da Recorrência.' },
          { title: 'Revise as condições', description: 'Em Condições da recorrência, ajuste Valor mensal, Dia de vencimento, Descrição, Forma de pagamento, percentuais e Mensagem do boleto conforme o contrato.' },
          { title: 'Configure as próximas competências', description: 'Confira Primeira competência, Dia de processamento e Competência da mensalidade. Para contratos anteriores sem configuração, preencha esses campos antes de ativar o agendamento.' },
          { title: 'Confira a NFS-e', description: 'Escolha Tratamento da NFS-e. O editor sugere gerar rascunho para revisão quando o contrato ainda não possui preferência; confira o ambiente, selecione o emitente do escritório e revise os dados fiscais antes de salvar.' },
          { title: 'Ative ou pause', description: 'Marque Ativar agendamento mensal para programar próximas competências; desmarque para pausar. Clique em Salvar configuração e aguarde a mensagem de confirmação.' },
        ],
        verification: ['Ao reabrir o contrato, os parâmetros e o estado do agendamento permanecem salvos.', 'Competências já geradas continuam com os dados originais; alterações valem para competências ainda não geradas.'],
        tips: ['Pausar o agendamento não cancela cobranças ou notas já geradas, nem desfaz uma operação já em processamento.', 'A primeira cobrança solicitada manualmente possui execução própria: confira Execuções por competência mesmo com agendamento pausado.'],
        related: ['faturamento-recorrencias', 'faturamento-recorrencia-execucoes'],
      },
      {
        id: 'faturamento-recorrencia-execucoes', title: 'Acompanhar e retomar uma competência',
        summary: 'Entenda a etapa de cada mensalidade e recupere uma operação sem duplicar a cobrança ou o RPS.',
        path: 'Faturamento → Recorrências → Execuções por competência',
        prerequisites: ['Recorrência salva; se necessário, abra o contrato para ver somente suas competências.'],
        steps: [
          { title: 'Localize a mensalidade', description: 'Em Execuções por competência, confira Competência, Etapa e Situação. A etapa indica Cobrança, Preparação da NFS-e, NFS-e ou Finalizada.' },
          { title: 'Leia a situação', description: 'Aguardando processamento e Em processamento indicam trabalho pendente. Precisa de atenção apresenta a mensagem da falha. Aguardando pagamento depende da confirmação do recebimento; Rascunho para revisar exige sua conferência fiscal.' },
          { title: 'Retome a mesma execução', description: 'Quando disponível, clique em Retomar execução e aguarde. O sistema conserva os identificadores da cobrança e do RPS. Depois de fechar ou recarregar a página, volte a essa competência para acompanhar o resultado.' },
          { title: 'Confira o rascunho', description: 'Se a situação for Rascunho para revisar, abra Histórico NFS-e, localize a nota e use Editar / revisar. Conferir ou salvar o rascunho ainda não transmite a nota.' },
          { title: 'Confira os documentos finais', description: 'Localize a cobrança em Financeiro e a nota em Histórico NFS-e. Compare parceiro, competência, valor e ambiente; abra a prévia PDF e confira o XML quando necessário.' },
        ],
        verification: ['A competência mantém uma única execução e os documentos estão associados ao parceiro correto.', 'Concluída deve ser interpretada conforme o tratamento escolhido: somente cobrança não inclui emissão de NFS-e.'],
        tips: ['Retomar não ignora pagamento pendente, revisão fiscal ou bloqueio de produção.', 'Se um vencimento ultrapassado impedir uma nova cobrança, revise a mensagem e o contrato; não crie outra competência apenas para contornar o bloqueio.', 'Uma tentativa fiscal incerta deve consultar o mesmo RPS antes de qualquer novo envio.'],
        related: ['faturamento-recorrencia-configurar', 'faturamento-nfse-historico', 'financeiro-receber'],
      },
      {
        id: 'faturamento-nfse-rascunho', title: 'Preparar, editar e revisar uma NFS-e',
        summary: 'Monte o rascunho fiscal, resolva pendências e confira a revisão antes de qualquer emissão.',
        path: 'Faturamento → Novo Lançamento → Somente NFS-e',
        prerequisites: ['Parceiro e cadastro fiscal do emitente conferidos.', 'Dados do serviço e enquadramento informados pelo responsável fiscal.'],
        steps: [
          { title: 'Escolha o fluxo', description: 'Selecione Somente NFS-e para preparar um rascunho independente. NFS-e + cobrança cria primeiro a cobrança e depois abre a preparação da nota vinculada.' },
          { title: 'Confira o contexto', description: 'Em Preparar NFS-e, escolha Ambiente, Emitente / configuração fiscal e o parceiro correto. Confira as notas anteriores disponíveis para esse parceiro.' },
          { title: 'Descreva a operação', description: 'Preencha Competência, Data de emissão do RPS, Descrição dos serviços e Valor dos serviços (R$).' },
          { title: 'Revise os dados fiscais', description: 'Confira Item da lista LC116, CNAE, Atividade / código municipal, NBS, municípios, ISS e retenções com o responsável fiscal. Não copie automaticamente dados de outra empresa.' },
          { title: 'Salve para revisar', description: 'Use Salvar rascunho para continuar depois ou Salvar e revisar para obter a Revisão do rascunho salvo. Leia os bloqueios e corrija os campos indicados.' },
          { title: 'Retome um rascunho', description: 'Em Histórico NFS-e, localize o registro e abra Editar / revisar quando disponível. Registros já confirmados podem permitir apenas Detalhes.' },
        ],
        verification: ['O rascunho salvo aparece no Histórico NFS-e.', 'A revisão identifica corretamente ambiente, emitente, tomador e valores; eventuais bloqueios estão resolvidos.'],
        tips: ['Salvar e revisar não transmite ao WebISS nem reserva número de RPS. Um rascunho salvo ainda não é uma nota autorizada.', 'Produção permite somente preparação nessa tela. A transmissão pelo rascunho está disponível apenas em homologação; ações fiscais vinculadas a cobranças têm um fluxo próprio.'],
        related: ['faturamento-nfse-homologacao', 'faturamento-nfse-historico', 'configuracoes-fiscal'],
      },
      {
        id: 'faturamento-nfse-homologacao', title: 'Transmitir um rascunho em homologação',
        summary: 'Realize uma emissão de teste após concluir a revisão do rascunho.',
        path: 'Faturamento → Preparar NFS-e → Transmitir em homologação',
        prerequisites: ['Integração de homologação pronta para emissão de teste.', 'Rascunho salvo e revisão sem bloqueios.'],
        steps: [
          { title: 'Confira o ambiente de teste', description: 'Em Preparar NFS-e, selecione Homologação (teste sem valor fiscal) e confira emitente e parceiro.' },
          { title: 'Atualize a revisão', description: 'Confira dados do serviço e use Salvar e revisar. Leia os bloqueios e resolva as pendências até a revisão permitir a transmissão.' },
          { title: 'Confirme a conferência', description: 'Marque Conferi os dados e quero transmitir esta nota em homologação somente após revisar o documento completo.' },
          { title: 'Transmita o teste', description: 'Clique em Transmitir em homologação e aguarde a mensagem de confirmação ou o erro retornado pelo provedor.' },
          { title: 'Confira o histórico', description: 'Localize a tentativa em Histórico NFS-e, com ambiente Homologação. Se a emissão não foi confirmada, consulte o mesmo RPS; quando disponíveis, baixe XML e PDF para revisar.' },
        ],
        verification: ['A confirmação e o registro indicam homologação.', 'O documento corresponde ao emitente, tomador e valores revisados.'],
        tips: ['O teste é sem valor fiscal. Produção (somente preparação) não libera transmissão nesse formulário.', 'Uma tentativa que já possui processamento fiscal deve ser consultada pelo mesmo RPS; não copie para outro rascunho para tentar novamente.'],
        related: ['faturamento-nfse-historico', 'financeiro-nfse-cobranca'],
      },
      {
        id: 'faturamento-nfse-historico', title: 'Consultar notas, RPS e baixar XML ou PDF',
        summary: 'Localize o documento fiscal e confira o retorno da prefeitura sem duplicar um lançamento.',
        path: 'Faturamento → Histórico NFS-e',
        prerequisites: ['Emitente e período que deseja consultar identificados.', 'Integração fiscal configurada para consultas externas.'],
        steps: [
          { title: 'Escolha os filtros', description: 'Informe Emitente, Parceiro / tomador, Ambiente e Status fiscal conforme a consulta. Você também pode pesquisar Número da nota ou nome.' },
          { title: 'Confira o período', description: 'Preencha Emissão de e Emissão até e clique em Filtrar. Limpar filtros permite iniciar uma nova pesquisa.' },
          { title: 'Identifique o parceiro', description: 'Confira o nome e o CPF/CNPJ apresentado abaixo dele. A lista mostra as notas registradas e importadas que correspondem aos filtros.' },
          { title: 'Abra e confira', description: 'Abra Detalhes ou Editar / revisar. Use Consultar o mesmo RPS quando a ação estiver habilitada para atualizar a situação municipal, inclusive de uma nota já confirmada. O sistema mantém o número do RPS e não faz uma nova emissão nessa consulta.' },
          { title: 'Visualize o PDF antes de baixar', description: 'Clique em Visualizar PDF para abrir a prévia em modal. Aguarde o carregamento e confira número, emitente, tomador, ambiente e valores. Use Baixar PDF dentro da prévia quando quiser salvar o arquivo; Fechar retorna ao histórico. O botão XML continua baixando o XML diretamente.' },
        ],
        verification: ['O status fiscal e o documento correspondem à operação pesquisada.', 'XML e PDF só ficam disponíveis quando o registro fornece o XML necessário.'],
        tips: ['Cancelamento WebISS está indisponível neste histórico. O botão desabilitado não cancela a nota.', 'Se houver tentativa pendente, consulte o mesmo RPS antes de iniciar outro lançamento.'],
      },
      {
        id: 'faturamento-monitoramento', title: 'Conferir faturamento, atrasos e links de cobrança',
        summary: 'Acompanhe o período, encontre pendências e recupere documentos de cobranças já criadas.',
        path: 'Faturamento → Dashboard / Inadimplência / Financeiro',
        prerequisites: ['Cobranças registradas no escritório.'],
        steps: [
          { title: 'Delimite o painel', description: 'No Dashboard, informe Data Inicial, Data Final, Parceiro/Empresa e Status Pagamento conforme a análise; aplique os filtros.' },
          { title: 'Leia os indicadores', description: 'Compare Total previsto, Total recebido, Total em aberto e Total em atraso. Os cartões fiscais apresentam NFS-e a emitir, emitidas e canceladas.' },
          { title: 'Localize atrasos', description: 'Abra Inadimplência, preencha Buscar Parceiro e o filtro Atraso. Confira os títulos apresentados antes de tratar a pendência com o cliente.' },
          { title: 'Recupere a cobrança', description: 'Na aba Financeiro, busque descrição, parceiro ou ID e confira o status. Use Copiar link, Baixar boleto ou Abrir página quando o documento estiver disponível.' },
        ],
        verification: ['Os filtros incluem o período e o parceiro desejados.', 'Você identificou quais títulos estão recebidos, em aberto ou em atraso.'],
        tips: ['Registrar contato, reenviar e cancelar estão indisponíveis na aba Inadimplência. Não considere um contato registrado ou uma cobrança cancelada por visualizar esses ícones.'],
      },
      {
        id: 'faturamento-padroes', title: 'Configurar padrões de faturamento',
        summary: 'Mantenha os dados padrão utilizados na preparação das cobranças e notas.',
        path: 'Faturamento → Configurações',
        prerequisites: ['Permissão para alterar parâmetros.', 'Definições fiscais revisadas pelo responsável do escritório.'],
        steps: [
          { title: 'Abra os padrões', description: 'Acesse a aba Configurações e leia as opções atuais de Configurações de Faturamento.' },
          { title: 'Confira parâmetros fiscais', description: 'Revise Código de Serviço Padrão (NFS-e), Alíquota ISS Padrão (%), Retenção INSS Padrão (%) e Regime de Tributação conforme o cadastro aplicável.' },
          { title: 'Ajuste os textos', description: 'Preencha Observação Padrão na NFS-e e Mensagem Padrão no E-mail de Cobrança (Recorrências) com textos aprovados pelo escritório.' },
          { title: 'Salve e confira', description: 'Clique em Salvar configurações, aguarde a confirmação e reabra a aba para conferir os valores registrados.' },
        ],
        verification: ['Os padrões permanecem salvos ao reabrir a aba.'],
        tips: ['Ter uma mensagem padrão cadastrada não comprova envio de e-mail. Confira o resultado de cada operação.', 'Padrões devem ser revisados no rascunho de cada nota; não substituem os dados específicos da operação.'],
      },
    ],
  },
  {
    id: 'financeiro', title: 'Financeiro', icon: 'Landmark',
    description: 'Controle recebimentos, despesas, movimentos entre contas e o saldo do escritório.',
    articles: [
      {
        id: 'financeiro-nfse-cobranca', title: 'Emitir ou reconciliar a NFS-e de uma cobrança',
        summary: 'Use as ações fiscais do recebível e confirme ambiente, RPS e resultado antes de baixar o documento.',
        path: 'Financeiro → Contas a Receber → ações de NFS-e da cobrança',
        prerequisites: ['Cobrança identificada e dados fiscais conferidos.', 'Integração fiscal habilitada no ambiente pretendido e operação revisada pelo responsável fiscal.'],
        steps: [
          { title: 'Identifique a cobrança', description: 'Abra Contas a Receber, localize o título e confira cliente, descrição, valor e eventual número de NFS-e ou RPS apresentado.' },
          { title: 'Confira o ambiente configurado', description: 'Antes de usar a emissão, confira a configuração fiscal do emitente. Esta ação usa o ambiente configurado e pode registrar uma nota de produção.' },
          { title: 'Consulte uma tentativa existente', description: 'Se houver RPS, nota ou processamento pendente, use Consultar RPS quando disponível e leia o retorno antes de solicitar outro envio.' },
          { title: 'Use a ação de emissão cabível', description: 'Para cobrança não cancelada e ainda sem nota confirmada, pode aparecer Emitir NFS-e ou Reconciliar / emitir. Ao acionar, aguarde o resultado; RPS pendentes são consultados antes de um novo envio.' },
          { title: 'Confira a confirmação e o PDF', description: 'Leia se o retorno indica homologação sem valor fiscal ou registro em produção. Com documento confirmado, use PDF da NFS-e e confira o arquivo.' },
        ],
        verification: ['O retorno fiscal informa o número da nota e o ambiente correto.', 'O PDF corresponde à cobrança e ao XML confirmado.'],
        tips: ['O fluxo por cobrança é diferente do formulário Preparar NFS-e, cuja transmissão se limita à homologação.', 'Em caso de erro ou resultado pendente, preserve a referência da cobrança e do RPS e consulte o mesmo registro antes de repetir a operação.'],
        related: ['faturamento-nfse-historico', 'configuracoes-fiscal'],
      },
      {
        id: 'financeiro-caixa', title: 'Entender e conferir o Caixa',
        summary: 'Leia os saldos e identifique os registros que explicam entradas, saídas e pendências.',
        path: 'Financeiro → Caixa', prerequisites: ['Contas bancárias e movimentações registradas.'],
        steps: [
          { title: 'Abra a visão geral', description: 'Acesse Financeiro e selecione Caixa. Aguarde o carregamento dos indicadores.' },
          { title: 'Leia saldos e compromissos', description: 'Confira Saldo Disponível, Contas a Receber e Contas a Pagar. Compare Receitas (Recebidas) e Despesas (Pagas) no contexto apresentado.' },
          { title: 'Veja a origem dos números', description: 'Consulte Saldos das Contas, Receitas por Parceiro e Despesas por Categoria para identificar onde os valores se concentram.' },
          { title: 'Confira os detalhes', description: 'Abra Contas a Receber, Contas a Pagar ou Lançamentos / Extrato para localizar os registros que precisam de conferência.' },
        ],
        verification: ['As contas e os movimentos esperados aparecem nas telas de detalhe.', 'Uma pendência foi conferida pelo registro de origem, além do total do cartão.'],
        tips: ['Se o carregamento falhar, use Tentar novamente. Uma falha de consulta não significa ausência de movimentação.'],
      },
      {
        id: 'financeiro-receber', title: 'Consultar recebíveis e registrar baixa manual',
        summary: 'Localize cobranças e registre um recebimento comprovado quando a baixa manual estiver disponível.',
        path: 'Financeiro → Contas a Receber',
        prerequisites: ['Cobrança existente e comprovante do recebimento.', 'Conta bancária de destino cadastrada para a baixa manual.'],
        steps: [
          { title: 'Localize o título', description: 'Busque descrição, cliente ou ID. Use os filtros da tela para separar recebidos, em aberto e em atraso.' },
          { title: 'Confira a identidade', description: 'Compare cliente, descrição, valor e vencimento com o comprovante. Você pode abrir ou copiar o link da cobrança quando disponível.' },
          { title: 'Abra a baixa', description: 'Quando habilitado, clique em Baixar, identificado como Dar baixa manual, para abrir Registrar Baixa Manual. Essa ação registra o recebimento; o download do boleto possui uma ação própria.' },
          { title: 'Informe o recebimento', description: 'Preencha Data de Recebimento, Forma de Recebimento e Conta Bancária Destino. Confira Valor Recebido, Desconto e Juros/Multa; use a opção de baixa parcial quando o recebimento for em partes.' },
          { title: 'Registre e verifique', description: 'Inclua Observações / Histórico e clique em Confirmar Baixa. Confira o status ou saldo restante do título e o lançamento correspondente.' },
        ],
        verification: ['O recebimento está associado ao cliente e à conta corretos.', 'Em baixa parcial, a parcela ainda devida continua identificável.'],
        tips: ['A baixa manual de cobranças Banco Inter está desabilitada enquanto o fluxo de cancelamento e conciliação não estiver disponível. Não registre uma segunda receita para forçar o status.'],
        related: ['faturamento-cobranca', 'financeiro-extrato'],
      },
      {
        id: 'financeiro-pagar-cadastro', title: 'Cadastrar contas a pagar e parcelas',
        summary: 'Registre uma despesa imediata ou um compromisso com vencimento futuro.',
        path: 'Financeiro → Contas a Pagar → Novo contas a pagar',
        prerequisites: ['Credor, valor e vencimento definidos.', 'Conta de saída cadastrada quando exigida pelo lançamento.'],
        steps: [
          { title: 'Abra o formulário', description: 'Na aba Contas a Pagar, clique em Novo contas a pagar.' },
          { title: 'Classifique a despesa', description: 'Escolha Tipo de Despesa e Status do Pagamento. Preencha Descrição / Credor e selecione a Categoria; o formulário permite cadastrar uma nova categoria.' },
          { title: 'Informe valores e datas', description: 'Preencha Valor do Lançamento e as datas apresentadas. Confira Data de Vencimento para uma despesa pendente e Conta de Origem (Saída) quando aplicável.' },
          { title: 'Confira o parcelamento', description: 'Se houver parcelas, selecione a opção em Opções de Parcelamento, informe Nº de Parcelas e confira os valores e datas apresentados antes de confirmar.' },
          { title: 'Registre a despesa', description: 'Clique em Confirmar Lançamento. Localize o credor pela busca e confira todos os registros criados, especialmente quando houver parcelamento.' },
        ],
        verification: ['A despesa aparece com categoria, valor, vencimento e status corretos.', 'As parcelas correspondem ao compromisso informado.'],
        related: ['financeiro-pagamento'],
      },
      {
        id: 'financeiro-pagamento', title: 'Registrar o pagamento de uma despesa',
        summary: 'Dê baixa em uma conta a pagar após conferir o pagamento efetivamente realizado.',
        path: 'Financeiro → Contas a Pagar → Registrar Pagamento',
        prerequisites: ['Despesa pendente cadastrada.', 'Pagamento e conta de origem conferidos com o comprovante.'],
        steps: [
          { title: 'Encontre a despesa', description: 'Pesquise descrição ou ID e confira o credor, o valor e o vencimento do título pendente.' },
          { title: 'Abra o pagamento', description: 'Use a ação de pagamento do título para abrir Registrar Pagamento.' },
          { title: 'Preencha a baixa', description: 'Selecione Conta de Origem, Data do Pagamento e informe Desconto (R$), Juros / Multa (R$) e Valor Total Pago (R$) conforme o comprovante.' },
          { title: 'Confirme o registro', description: 'Preencha Observações / Comprovante com uma referência útil e clique em Confirmar Pagamento. Aguarde a conclusão.' },
          { title: 'Confira o efeito', description: 'Verifique o status Pago e confira o movimento na conta em Lançamentos / Extrato e Caixa.' },
        ],
        verification: ['O título está marcado como Pago e os dados refletem o comprovante.'],
        tips: ['Registrar Pagamento é um registro financeiro no sistema; não substitui a execução do pagamento no banco.'],
      },
      {
        id: 'financeiro-extrato', title: 'Registrar créditos, débitos e transferências',
        summary: 'Controle movimentos avulsos e consulte o extrato interno por conta, período e tipo.',
        path: 'Financeiro → Lançamentos / Extrato',
        prerequisites: ['Contas bancárias cadastradas.', 'Origem, destino e documento do movimento conferidos.'],
        steps: [
          { title: 'Confira registros existentes', description: 'Use a busca por descrição, banco ou valor e os filtros de datas. Alterne entre Todos os lançamentos, Créditos avulsos, Débitos avulsos e Transferências.' },
          { title: 'Escolha a operação', description: 'Abra a ação de novo crédito, novo débito ou transferência conforme o movimento que precisa registrar.' },
          { title: 'Registre entrada ou saída', description: 'Para crédito ou débito, preencha Data, Valor (R$), Descrição e Categoria. Selecione Conta de Destino (Entrada) ou Conta de Origem (Saída), respectivamente.' },
          { title: 'Registre uma transferência', description: 'Em Transferência entre Contas, informe Data, Valor (R$), contas de origem e destino diferentes e Descrição / Observação.' },
          { title: 'Confirme e confira', description: 'Use Confirmar Crédito, Confirmar Débito ou Confirmar Transferência conforme a operação. Confira a linha no extrato e os saldos das contas.' },
        ],
        verification: ['Tipo, data, valor e contas correspondem ao movimento desejado.', 'A busca não apresenta um segundo lançamento para o mesmo movimento.'],
        tips: ['Transferência entre Contas registra a movimentação interna; execute e confira a transferência bancária pelos canais apropriados.', 'Não use crédito avulso para repetir um recebimento que já foi registrado na baixa da cobrança.'],
        related: ['configuracoes-contas', 'financeiro-caixa'],
      },
    ],
  },
];
