import type { GuideArticle } from '../types';

export const PARAMETRIZACAO_ARTICLES: GuideArticle[] = [
  {
    id: 'param-regimes', title: 'Regimes Tributários: consultar e editar informações',
    summary: 'Mantenha a descrição, o limite informado, as vantagens e as restrições do catálogo de regimes.',
    path: 'Parametrização → Regimes Tributários', prerequisites: ['Ter acesso à parametrização e as informações que serão registradas.'],
    steps: [
      { title: 'Selecione um regime', description: 'Expanda Parametrização no menu e abra Regimes Tributários. Clique na aba do regime desejado e confira o título completo do painel.' },
      { title: 'Leia o cadastro', description: 'Consulte Limite de Faturamento, descrição, vantagens e restrições antes de alterar o texto.' },
      { title: 'Abra a edição', description: 'Clique em Editar Regime. Preencha Nome do regime, Limite de faturamento e Descrição geral.' },
      { title: 'Organize as orientações', description: 'Nas listas Vantagens e Restrições, edite os textos e use Adicionar para incluir mais itens.' },
      { title: 'Salve e revise', description: 'Clique em Salvar Alterações. Confira se o painel do regime apresenta os textos atualizados.' },
    ],
    verification: ['O regime selecionado e seus textos estão corretos após salvar.'],
    tips: ['Esse editor mantém as informações do catálogo. Para mudar o regime de uma empresa, edite o cadastro do parceiro.'],
    related: ['parceiros-editar', 'param-tabelas'],
  },
  {
    id: 'param-enquadramento', title: 'Tipos de Empresa: manter portes e enquadramentos',
    summary: 'Organize as opções utilizadas no campo Porte / enquadramento do cadastro de parceiros.',
    path: 'Parametrização → Tipos de Empresa → Enquadramento', prerequisites: ['Identificar o porte ou enquadramento que precisa ficar disponível.'],
    steps: [
      { title: 'Abra Enquadramento', description: 'No menu Parametrização, clique em Tipos de Empresa. A página aberta tem o título Enquadramento.' },
      { title: 'Procure antes de criar', description: 'Use a busca para verificar se a opção já existe, incluindo MEI, ME, EPP e Demais.' },
      { title: 'Crie ou edite', description: 'Clique em Novo Registro ou no ícone Editar registro da linha existente.' },
      { title: 'Preencha o parâmetro', description: 'Informe Nome do Parâmetro, Descrição detalhada e Status. Deixe a opção ativa quando ela deva ser usada em novos cadastros.' },
      { title: 'Salve e confira', description: 'Clique em Salvar Parâmetro. Confira Nome, Descrição e Status na lista e depois no campo Porte / enquadramento de Parceiros.' },
    ],
    verification: ['O enquadramento aparece na lista com o status esperado.'],
    tips: ['Porte, natureza jurídica e regime são classificações distintas no cadastro.', 'Ativar parâmetro e Desativar parâmetro controlam sua disponibilidade; a ação Inativar registro também inativa.'],
    related: ['parceiros-cadastrar-pj', 'param-natureza'],
  },
  {
    id: 'param-natureza', title: 'Natureza Jurídica: cadastrar e manter o catálogo',
    summary: 'Disponibilize a classificação jurídica usada no cadastro de pessoas jurídicas.',
    path: 'Parametrização → Natureza Jurídica', prerequisites: ['Nome e descrição da natureza jurídica a registrar.'],
    steps: [
      { title: 'Pesquise a natureza', description: 'Abra Natureza Jurídica e busque pelo nome ou pela descrição para evitar registros repetidos.' },
      { title: 'Abra o formulário', description: 'Use Novo Registro para incluir uma opção ou Editar registro para corrigir uma existente.' },
      { title: 'Descreva o uso', description: 'Preencha Nome do Parâmetro e Descrição detalhada. Defina o Status desejado.' },
      { title: 'Grave o cadastro', description: 'Clique em Salvar Parâmetro. Se houver mensagem de erro, corrija os dados e tente novamente.' },
      { title: 'Confira a disponibilidade', description: 'Confira a linha salva e use Ativar parâmetro ou Desativar parâmetro quando precisar alterar sua disponibilidade.' },
    ],
    verification: ['A opção ativa aparece no campo Natureza jurídica do formulário de parceiro com CNPJ.'],
    tips: ['Para parceiro com CPF, o formulário informa que natureza jurídica não se aplica.'],
    related: ['parceiros-cadastrar-pj'],
  },
  {
    id: 'param-tipos-parceiros', title: 'Tipos de Parceiros: definir o relacionamento',
    summary: 'Classifique cadastros como cliente contábil, fornecedor, correspondente ou outro relacionamento.',
    path: 'Parametrização → Tipos de Parceiros', prerequisites: ['Definir como o escritório distinguirá seus relacionamentos.'],
    steps: [
      { title: 'Consulte os tipos', description: 'Abra Tipos de Parceiros e pesquise o relacionamento que deseja usar.' },
      { title: 'Inclua uma opção ausente', description: 'Clique em Novo Registro. Para corrigir um tipo existente, use Editar registro.' },
      { title: 'Preencha o registro', description: 'Informe Nome do Parâmetro, Descrição detalhada e Status. Explique na descrição a quem o tipo se destina.' },
      { title: 'Salve o tipo', description: 'Clique em Salvar Parâmetro e confira o registro na tabela.' },
      { title: 'Use no parceiro', description: 'Abra um cadastro em Parceiros e selecione a opção em Tipo de parceiro. Salve o cadastro do parceiro para aplicar a classificação.' },
    ],
    verification: ['O tipo aparece ativo no catálogo e pode ser selecionado no cadastro do parceiro.'],
    tips: ['Cliente Contábil é um tipo obrigatório do sistema e sua inativação é bloqueada.', 'A seleção de Cliente Contábil habilita a categoria do cliente e as rotinas específicas no detalhe. Um novo tipo personalizado não substitui automaticamente essa função.'],
    related: ['parceiros-cadastrar-pj', 'parceiros-obrigacoes'],
  },
  {
    id: 'param-categorias-clientes', title: 'Categorias de Clientes: organizar a carteira contábil',
    summary: 'Crie categorias para classificar clientes contábeis e mantenha as opções disponíveis no cadastro.',
    path: 'Parametrização → Categorias de Clientes', prerequisites: ['Definir um nome e uma finalidade para a categoria.'],
    steps: [
      { title: 'Procure uma categoria existente', description: 'Abra Categorias de Clientes e use Buscar por nome ou descrição.' },
      { title: 'Crie a categoria', description: 'Clique em Nova Categoria. Informe Nome e Descrição com a finalidade do agrupamento.' },
      { title: 'Grave o registro', description: 'Clique em Salvar Categoria. Confira a nova opção na lista.' },
      { title: 'Edite ou altere a disponibilidade', description: 'Use Editar categoria para corrigir os textos e Ativar categoria ou Inativar categoria para controlar a disponibilidade.' },
      { title: 'Classifique o cliente', description: 'No cadastro de um parceiro do tipo Cliente Contábil, escolha a Categoria do cliente ativa e salve o parceiro.' },
    ],
    verification: ['A categoria está ativa na lista e selecionada no cliente correto.'],
    tips: ['Categoria do cliente é um agrupamento da carteira; ela é separada de Tipo de parceiro, Regime tributário e Porte / enquadramento.'],
    related: ['parceiros-cadastrar-pj', 'parceiros-editar'],
  },
  {
    id: 'param-cnae', title: 'CNAE: pesquisar atividades e controlar a disponibilidade',
    summary: 'Consulte a classificação das atividades econômicas e escolha quais ficam disponíveis para o escritório.',
    path: 'Parametrização → CNAE', prerequisites: ['Código da atividade ou uma descrição para pesquisar.'],
    steps: [
      { title: 'Busque a atividade', description: 'Abra CNAE e preencha Buscar por código, atividade ou ocupação MEI.' },
      { title: 'Ajuste os filtros', description: 'Use Todos, MEI, Simples Nacional, Lucro Presumido, Lucro Real ou Inativos conforme a consulta.' },
      { title: 'Leia a classificação', description: 'Confira código, descrição, observações, MEI, Regimes permitidos, Anexos do Simples e Presunção na linha.' },
      { title: 'Consulte a origem da informação', description: 'Use Fonte CNAE ou Fonte tributária quando precisar abrir as referências vinculadas à atividade.' },
      { title: 'Controle a disponibilidade', description: 'Na coluna Disponibilidade, clique em Ativo ou Inativo para alternar o status. Aguarde a confirmação e confira a linha.' },
    ],
    verification: ['A atividade consultada possui o código desejado e o status esperado.'],
    tips: ['O catálogo padrão é protegido: esta tela permite consultar e ativar/inativar, sem editar ou excluir as regras padrão.', 'Quando houver vários anexos, leia as observações da atividade e as condições indicadas antes de usar a classificação.'],
    related: ['parceiros-cadastrar-pj', 'param-impostos'],
  },
  {
    id: 'param-impostos', title: 'Impostos: cadastrar regras de PIS e COFINS',
    summary: 'Registre as regras fiscais por regime e atividade, com CST e alíquotas informadas pelo responsável.',
    path: 'Parametrização → Impostos → Impostos (PIS/COFINS)', prerequisites: ['CNAE disponível e os parâmetros fiscais que serão cadastrados.'],
    steps: [
      { title: 'Abra a aba de impostos', description: 'Em Parametrização → Impostos, selecione Impostos (PIS/COFINS).' },
      { title: 'Crie uma regra', description: 'Clique em Nova Regra de Imposto e informe Nome Identificador da Regra.' },
      { title: 'Defina o contexto', description: 'Selecione Regime Tributário e Atividade CNAE Associada. Confira se escolheu a atividade correta.' },
      { title: 'Informe a tributação', description: 'Preencha CST PIS, Alíquota PIS (%), CST COFINS e Alíquota COFINS (%) com os valores definidos para a regra.' },
      { title: 'Salve e revise', description: 'Clique em Criar Regra. Confira a regra na tabela e use Editar Regra se precisar corrigir algum parâmetro.' },
    ],
    verification: ['Nome, regime, CNAE, CST e alíquotas correspondem aos parâmetros pretendidos.'],
    tips: ['O formulário oferece Lucro Presumido e Lucro Real. Não escolha um regime diferente apenas para conseguir salvar.', 'Cadastrar uma regra mantém o parâmetro no sistema; a tela não envia uma declaração fiscal.'],
    related: ['param-cnae'],
  },
  {
    id: 'param-regras-financeiras', title: 'Regras Financeiras: parâmetros de cobrança e conciliação',
    summary: 'Cadastre uma regra CNAB para cobrança ou para identificar transações de extrato.',
    path: 'Parametrização → Impostos → Regras Financeiras', prerequisites: ['Banco e parâmetros de cobrança ou identificação de extrato definidos.'],
    steps: [
      { title: 'Abra Regras Financeiras', description: 'Dentro de Impostos, selecione Regras Financeiras e clique em Nova Regra CNAB.' },
      { title: 'Identifique a regra', description: 'Preencha Nome Identificador da Regra e selecione Instituição Bancária.' },
      { title: 'Escolha a finalidade', description: 'Em Tipo de Regra Bancária, escolha Conciliação Automática de Extrato ou Geração de Cobrança (Juros/Multa).' },
      { title: 'Complete os campos da finalidade', description: 'Para cobrança, informe Multa por Atraso (%), Juros Mensais (%) e Dias de Tolerância. Para conciliação, informe Texto a buscar no Extrato e Conta de Contrapartida Contábil.' },
      { title: 'Grave e confira', description: 'Clique em Criar Regra CNAB. Confira a regra na tabela e use Editar Regra para ajustes posteriores.' },
    ],
    verification: ['A regra está vinculada ao banco correto e apresenta o tipo e os parâmetros desejados.'],
    tips: ['Esta tela cadastra parâmetros. A geração de cobranças e a importação de extratos são operações dos módulos correspondentes.'],
  },
  {
    id: 'param-calculo', title: 'Parâmetros de Cálculo: configurar motivos de rescisão',
    summary: 'Defina o nome, a explicação, a visibilidade e os efeitos de cada motivo usado pela calculadora.',
    path: 'Parametrização → Parâmetros de Cálculo → Motivos de rescisão', prerequisites: ['Definir quais opções e efeitos a calculadora deve utilizar.'],
    steps: [
      { title: 'Abra os motivos', description: 'Entre em Parâmetros de Cálculo. Confira o resumo de motivos ativos e a Última revisão.' },
      { title: 'Ajuste os textos', description: 'No cartão do motivo desejado, edite Nome exibido e Explicação para o usuário.' },
      { title: 'Defina a visibilidade', description: 'Use o controle Ativo/Oculto. Ativo deixa o motivo visível no cálculo; Oculto o retira da seleção.' },
      { title: 'Revise os efeitos', description: 'Em Efeitos no cálculo, confira as opções Aviso prévio e Multa do FGTS e marque as que devem ser incluídas.' },
      { title: 'Salve a configuração', description: 'Com Alterações pendentes, clique em Salvar alterações. Aguarde a mensagem de resultado e o estado Configuração sincronizada.' },
    ],
    verification: ['O resumo de ativos e os cartões refletem as alterações salvas.', 'Na calculadora de rescisão, confira os nomes e motivos disponibilizados.'],
    tips: ['Revise todos os cartões alterados antes de salvar, pois a configuração é usada pela calculadora.'],
    related: ['param-tabelas'],
  },
  {
    id: 'param-tabelas', title: 'Tabelas Tributárias: consultar vigência e faixas',
    summary: 'Consulte os parâmetros versionados usados pela Calculadora de Rescisão para uma competência.',
    path: 'Parametrização → Tabelas Tributárias', prerequisites: ['Saber o mês e o ano que deseja consultar.'],
    steps: [
      { title: 'Selecione a competência', description: 'Abra Tabelas Tributárias e ajuste Competência consultada para o mês e ano desejados.' },
      { title: 'Escolha a categoria', description: 'Use Rescisão para a visão geral ou as abas IRRF mensal e INSS para restringir a consulta.' },
      { title: 'Confira a versão', description: 'No cartão, leia origem Oficial/Escritório, Versão e Vigência. Confira se o período corresponde à competência consultada.' },
      { title: 'Leia os parâmetros', description: 'Consulte as faixas, os limites, as alíquotas, as deduções e demais configurações exibidas.' },
      { title: 'Atualize ou abra a fonte', description: 'Use Atualizar para recarregar os dados e Fonte para abrir a referência vinculada quando disponível.' },
    ],
    verification: ['Há parâmetros vigentes para a categoria e competência selecionadas.', 'A versão, vigência e origem foram conferidas antes de comparar um cálculo.'],
    tips: ['O catálogo oficial é protegido e não possui edição nesta página.', 'Nenhum parâmetro vigente encontrado significa ausência de dados para aquele filtro; confira categoria e competência.'],
    related: ['param-calculo'],
  },
  {
    id: 'param-obrigacoes', title: 'Obrigações: criar modelos, etapas e regimes aplicáveis',
    summary: 'Monte o catálogo de obrigações que depois poderão ser selecionadas em cada cliente e unidade.',
    path: 'Parametrização → Obrigações', prerequisites: ['Nome, finalidade, periodicidade, etapas e regimes aos quais a obrigação se aplica.'],
    steps: [
      { title: 'Pesquise no catálogo', description: 'Abra Obrigações. Busque por obrigação, categoria ou etapa e use os filtros Regime, Categoria e Status para verificar se o modelo já existe.' },
      { title: 'Abra o editor', description: 'Clique em Nova obrigação para criar ou em Editar no cartão para ajustar um modelo existente.' },
      { title: 'Preencha a identificação', description: 'Informe Nome da obrigação, Categoria, Órgão, Origem padrão e Descrição. A origem distingue envio do cliente, envio do escritório ou ambos.' },
      { title: 'Defina a agenda', description: 'Em Prazo e período, escolha o Período e indique se Possui vencimento. Preencha os campos de dia, mês ou data que aparecerem para a periodicidade escolhida.' },
      { title: 'Selecione a aplicação', description: 'Em Regimes aplicáveis, marque onde a obrigação poderá ser ativada. Confira se o regime dos clientes pretendidos está incluído.' },
      { title: 'Organize o trabalho', description: 'Em Etapas do fluxo, use Adicionar etapa, descreva cada ação e ordene pelas setas Mover etapa para cima/baixo. Remova etapas desnecessárias pelo ícone próprio.' },
      { title: 'Grave e vincule aos clientes', description: 'Clique em Salvar obrigação e confira o cartão. Depois abra o cliente em Parceiros → Rotinas e Obrigações e salve a seleção da obrigação para cada unidade aplicável.' },
    ],
    verification: ['O cartão mostra nome, regime, período, prazo e etapas esperados.', 'A obrigação ativa fica disponível para seleção nas unidades aplicáveis.'],
    tips: ['Duplicar cria uma base a partir de outro modelo; revise nome, prazo, regimes e etapas antes de salvar.', 'O controle Ativar/Desativar obrigação muda a disponibilidade do modelo. Leia a confirmação exibida antes de concluir.', 'Criar o modelo e selecioná-lo no cliente são etapas distintas do processo.'],
    related: ['param-obrigacoes-prazos', 'parceiros-obrigacoes'],
  },
  {
    id: 'param-obrigacoes-prazos', title: 'Obrigações: configurar periodicidade e vencimentos',
    summary: 'Entenda os campos de agenda e a diferença entre período da rotina, competência e prazo.',
    path: 'Parametrização → Obrigações → Nova obrigação ou Editar → Prazo e período', prerequisites: ['Modelo de obrigação aberto no editor e agenda definida para ele.'],
    steps: [
      { title: 'Escolha o período', description: 'No campo Período, selecione a frequência real da rotina: diária, semanal, quinzenal, mensal, trimestral, semestral, anual ou única, conforme as opções da tela.' },
      { title: 'Defina se há prazo', description: 'Marque Possui vencimento quando houver prazo a acompanhar. Sem vencimento, o período continua organizando a rotina.' },
      { title: 'Preencha dia, mês ou data', description: 'Para semanal, escolha Dia da execução. Para anual, informe Mês da ocorrência e Dia da ocorrência. Para única, informe Data da ocorrência, inclusive quando não há prazo fiscal.' },
      { title: 'Configure os vencimentos recorrentes', description: 'Com vencimento ativo, a periodicidade quinzenal pede 1ª quinzena e 2ª quinzena; mensal, trimestral e semestral usam Dia do vencimento. A diária não pede outro campo de agenda.' },
      { title: 'Confira a competência', description: 'Quando disponível, marque Competência do mês anterior se a entrega trata do mês anterior ao vencimento. Exemplo: vencimento em maio acompanhando a competência de abril.' },
      { title: 'Salve e revise o resumo', description: 'Clique em Salvar obrigação. Confira a descrição do prazo no cartão e na configuração de obrigações do cliente.' },
    ],
    verification: ['Período, campos de ocorrência e opção de competência correspondem à agenda pretendida.'],
    tips: ['Uma rotina sem vencimento ainda precisa dos campos de ocorrência apresentados para período semanal, anual ou único.'],
    related: ['param-obrigacoes', 'parceiros-obrigacoes'],
  },
  {
    id: 'param-tipos-documentos', title: 'Tipos de Documentos: padronizar a classificação',
    summary: 'Mantenha o catálogo de tipos para identificar e organizar os documentos do escritório.',
    path: 'Parametrização → Tipos de Documentos', prerequisites: ['Nome e finalidade do tipo de documento.'],
    steps: [
      { title: 'Pesquise o tipo', description: 'Abra Tipos de Documentos e use a busca por nome ou descrição.' },
      { title: 'Crie ou edite', description: 'Clique em Novo Tipo ou no ícone Editar tipo do registro existente.' },
      { title: 'Preencha a classificação', description: 'Informe Nome, Descrição e marque Tipo ativo para disponibilizá-lo.' },
      { title: 'Salve o registro', description: 'Clique em Salvar Tipo e confira o nome, a descrição e a situação na lista.' },
      { title: 'Mantenha a disponibilidade', description: 'Use Inativar tipo ou Ativar tipo quando uma classificação deixar de ser usada ou precisar voltar ao catálogo.' },
    ],
    verification: ['O tipo aparece no catálogo com a situação esperada.'],
    tips: ['Tipo de documento classifica um arquivo. Pastas Padrão define a estrutura de armazenamento e possui uma configuração própria.'],
    related: ['param-pastas'],
  },
  {
    id: 'param-pastas', title: 'Pastas Padrão: criar e aplicar a estrutura documental',
    summary: 'Defina pastas sugeridas no cadastro e aplique a estrutura aos clientes existentes quando necessário.',
    path: 'Parametrização → Pastas Padrão', prerequisites: ['Definir a estrutura de pastas e subpastas usada pelo escritório.'],
    steps: [
      { title: 'Revise a estrutura existente', description: 'Abra Pastas Padrão e procure por pasta ou descrição antes de adicionar uma opção.' },
      { title: 'Crie uma pasta', description: 'Clique em Nova Pasta. Preencha Caminho da pasta, usando / para indicar subpastas, por exemplo Societario/Documentos dos Socios.' },
      { title: 'Descreva e disponibilize', description: 'Preencha Descrição e marque Pasta ativa para novos clientes se ela deve aparecer na estrutura sugerida.' },
      { title: 'Salve a pasta', description: 'Clique em Salvar Pasta. Para ajustes posteriores, use Editar pasta ou Ativar/Inativar pasta na lista.' },
      { title: 'Aplique aos clientes existentes, se necessário', description: 'Revise as pastas ativas e clique em Aplicar em clientes quando quiser aplicar o padrão à carteira existente. Aguarde o resultado informado pela tela.' },
      { title: 'Confira na operação', description: 'No cadastro de um novo parceiro, verifique as opções da etapa Pastas. Para clientes existentes, consulte a estrutura no módulo Documentos.' },
    ],
    verification: ['O caminho foi salvo com a hierarquia desejada.', 'A etapa de pastas do cadastro apresenta as opções ativas e o resultado da aplicação foi conferido.'],
    tips: ['Aplicar em clientes é uma ação sobre a carteira existente; confira a estrutura antes de acioná-la.'],
    related: ['parceiros-cadastrar-pj', 'param-tipos-documentos'],
  },
  {
    id: 'param-categorias-financeiras', title: 'Categorias Financeiras: organizar despesas fixas e variáveis',
    summary: 'Cadastre categorias para classificar despesas e mantenha sua disponibilidade.',
    path: 'Parametrização → Categorias Financeiras', prerequisites: ['Nome da categoria e definição de despesa fixa ou variável.'],
    steps: [
      { title: 'Consulte a lista', description: 'Abra Categorias Financeiras. Use Buscar categoria e confira os grupos Despesas Fixas e Despesas Variáveis.' },
      { title: 'Inicie o cadastro', description: 'Clique em Nova Categoria e preencha Nome da categoria.' },
      { title: 'Defina o grupo', description: 'No campo Tipo de despesa, escolha Despesa Fixa ou Despesa Variável.' },
      { title: 'Crie a categoria', description: 'Clique em Criar categoria. Confira se ela aparece no grupo escolhido.' },
      { title: 'Faça ajustes posteriores', description: 'Use o ícone Editar da categoria para alterar nome ou tipo e clique em Salvar alterações. Use Ativar/Inativar para controlar a disponibilidade.' },
    ],
    verification: ['A categoria aparece no grupo de despesas correto e com o status esperado.'],
    tips: ['Categorias Financeiras classificam despesas; Categorias de Clientes organizam a carteira contábil.'],
  },
];
