import type { GuideArticle } from '../types';

export const PARCEIROS_ARTICLES: GuideArticle[] = [
  {
    id: 'parceiros-localizar', title: 'Encontrar e consultar um parceiro',
    summary: 'Localize empresas e pessoas da carteira, confira o cadastro e identifique os recursos disponíveis para cada tipo de parceiro.',
    path: 'Parceiros', prerequisites: ['Ter acesso ao módulo Parceiros.'],
    steps: [
      { title: 'Abra a carteira', description: 'Clique em Parceiros no menu lateral. A tela reúne os cadastros do escritório.' },
      { title: 'Escolha a situação', description: 'Use Ativos ou Inativos. Um cadastro inativado deve ser procurado em Inativos.' },
      { title: 'Pesquise o cadastro', description: 'Digite o nome, razão social ou documento na busca. Ajuste o filtro de regime tributário; se não encontrar o parceiro, retire os filtros.' },
      { title: 'Escolha como visualizar', description: 'Alterne pelos ícones de cartões ou tabela. Abra o parceiro desejado para consultar Dados Cadastrais.' },
      { title: 'Confira a identidade', description: 'Compare nome, razão social, CPF/CNPJ, regime, categoria e status. Veja também os contatos e o endereço antes de iniciar uma operação.' },
    ],
    verification: ['O CPF/CNPJ e o nome correspondem ao parceiro pretendido.', 'Clientes contábeis exibem Rotinas e Obrigações; outros tipos de parceiro exibem os dados cadastrais.'],
    related: ['parceiros-cadastrar-pj', 'parceiros-editar'],
  },
  {
    id: 'parceiros-cadastrar-pj', title: 'Cadastrar empresa, cliente contábil ou fornecedor',
    summary: 'Cadastre uma pessoa jurídica em quatro etapas: identificação, contato, endereço e pastas.',
    path: 'Parceiros → Adicionar Parceiro',
    prerequisites: ['CNPJ e dados cadastrais da empresa.', 'Definir o tipo de relacionamento com o escritório e as classificações da empresa.'],
    steps: [
      { title: 'Inicie o cadastro', description: 'Em Parceiros, clique em Adicionar Parceiro. Mantenha CNPJ como tipo de documento.' },
      { title: 'Consulte o CNPJ', description: 'Informe o CNPJ e clique em Buscar. Confira os dados preenchidos; a consulta auxilia o cadastro e ainda será necessário salvar o parceiro. Se houver falha na consulta, confira o documento e complete os campos disponíveis.' },
      { title: 'Preencha a identificação', description: 'Informe Razão social e Nome fantasia. Confira CNAE, Descrição do CNAE principal, IE / IM e Capital social, quando aplicáveis.' },
      { title: 'Classifique corretamente', description: 'Selecione Regime tributário, Tipo de parceiro, Porte / enquadramento e Natureza jurídica. Para Cliente Contábil, escolha também uma Categoria do cliente ativa. MEI deve usar Simples Nacional no regime e MEI no enquadramento.' },
      { title: 'Complete contato e endereço', description: 'Clique em Avançar para preencher contato, telefone e e-mail; avance novamente para endereço, bairro, CEP, cidade e UF. Use Voltar para corrigir a etapa anterior.' },
      { title: 'Escolha as pastas', description: 'Na última etapa, marque as pastas que deseja disponibilizar para os documentos. Use Selecionar todas ou Limpar quando necessário.' },
      { title: 'Salve e confira', description: 'Clique em Salvar Parceiro, aguarde a conclusão e localize o cadastro na lista. Abra Dados Cadastrais para confirmar as informações gravadas.' },
    ],
    verification: ['O parceiro aparece na carteira com o documento correto.', 'Tipo de parceiro, regime, enquadramento e natureza jurídica estão corretos.', 'Se for Cliente Contábil, a aba Rotinas e Obrigações está disponível.'],
    tips: ['Tipo de parceiro define o relacionamento; enquadramento indica o porte; natureza jurídica indica a forma jurídica; categoria organiza os clientes contábeis.', 'Os botões + junto às classificações permitem cadastrar uma opção ausente. Evite criar nomes duplicados.', 'Se aparecer erro ao carregar classificações ou categorias, use Tentar novamente e aguarde antes de avançar.'],
    related: ['param-tipos-parceiros', 'param-enquadramento', 'param-natureza', 'param-categorias-clientes', 'parceiros-obrigacoes'],
  },
  {
    id: 'parceiros-cadastrar-pf', title: 'Cadastrar uma pessoa física',
    summary: 'Registre um parceiro com CPF, nome completo, apelido e seus contatos.',
    path: 'Parceiros → Adicionar Parceiro → CPF', prerequisites: ['CPF, nome e dados de contato da pessoa.'],
    steps: [
      { title: 'Escolha CPF', description: 'Clique em Adicionar Parceiro e altere o tipo de documento para CPF antes de preencher a identificação.' },
      { title: 'Preencha os dados pessoais', description: 'Informe CPF, Nome completo e Apelido. O regime fica como Pessoa física e o enquadramento de pessoa física é selecionado pelo formulário.' },
      { title: 'Defina o relacionamento', description: 'Selecione Tipo de parceiro. Se escolher Cliente Contábil, selecione também uma Categoria do cliente ativa. Natureza jurídica aparece como não aplicável à pessoa física.' },
      { title: 'Avance pelas etapas', description: 'Use Avançar para preencher contato e endereço. Na etapa de pastas, marque a estrutura documental desejada.' },
      { title: 'Grave o cadastro', description: 'Clique em Salvar Parceiro. Abra o parceiro na carteira e confira CPF, nome, apelido, contato e classificação.' },
    ],
    verification: ['O detalhe identifica o documento como CPF.', 'Os dados correspondem à pessoa cadastrada e o regime aparece como pessoa física.'],
    tips: ['A busca automática do botão Buscar é oferecida para CNPJ. Os dados da pessoa física devem ser preenchidos no formulário.', 'O cadastro com CPF não oferece gerenciamento de filiais.'],
    related: ['parceiros-editar', 'param-categorias-clientes'],
  },
  {
    id: 'parceiros-editar', title: 'Editar cadastro, logotipo e situação do parceiro',
    summary: 'Atualize informações existentes e consulte novamente o resultado da alteração.',
    path: 'Parceiros → parceiro → Dados Cadastrais', prerequisites: ['Parceiro já cadastrado e identificado pelo documento.'],
    steps: [
      { title: 'Abra o parceiro correto', description: 'Pesquise na carteira e compare o CPF/CNPJ no detalhe antes de editar.' },
      { title: 'Entre na edição', description: 'Na aba Dados Cadastrais, clique em Editar Cadastro. Ajuste identificação, classificações, contato ou endereço.' },
      { title: 'Revise as classificações', description: 'Confira Tipo de parceiro e Regime tributário. Para Cliente Contábil, mantenha uma Categoria do cliente ativa; para CNPJ, revise também Porte / enquadramento e Natureza jurídica.' },
      { title: 'Salve os dados', description: 'Clique em Salvar Alterações e aguarde a conclusão. Use Cancelar se quiser sair do formulário sem gravar as alterações atuais.' },
      { title: 'Atualize o logotipo, se necessário', description: 'No detalhe, clique na imagem ou nas iniciais com a indicação Alterar Logotipo, selecione uma imagem e aguarde o envio.' },
      { title: 'Ajuste a situação, se necessário', description: 'Use Inativar ou Reativar no topo do detalhe. Aguarde o resultado e confira o status e a presença do parceiro na aba Ativos ou Inativos da carteira.' },
    ],
    verification: ['Reabra Dados Cadastrais e confirme os campos alterados.', 'Verifique a mensagem de resultado; em caso de erro, corrija o campo informado antes de repetir.'],
    tips: ['Sincronizar CNAE aparece para pessoa jurídica sem CNAE informado; após a consulta, confira o código recebido.', 'Alterar o tipo de parceiro pode mudar as abas disponíveis. Revise a classificação antes de salvar.'],
    related: ['parceiros-localizar', 'parceiros-obrigacoes'],
  },
  {
    id: 'parceiros-filiais', title: 'Cadastrar, editar e inativar filiais',
    summary: 'Organize unidades vinculadas à matriz de um cliente contábil e mantenha seus contatos separados.',
    path: 'Parceiros → matriz → Filiais',
    prerequisites: ['Cliente Contábil cadastrado como matriz, pessoa jurídica e com CNPJ válido.', 'CNPJ e dados próprios da filial.'],
    steps: [
      { title: 'Abra a matriz', description: 'Localize o cliente contábil e entre na aba Filiais. Ela aparece quando o cadastro atende aos requisitos de matriz com CNPJ válido.' },
      { title: 'Adicione uma unidade', description: 'Clique em Adicionar Filial ou Cadastrar Primeira Filial quando a lista estiver vazia.' },
      { title: 'Informe a filial', description: 'Preencha CNPJ da Filial e use Buscar se desejar consultar os dados. Confira Nome da Filial, que é obrigatório.' },
      { title: 'Complete os contatos', description: 'Informe Nome do Contato, Telefone, E-mail, CEP, Endereço, Bairro, Cidade e UF da unidade.' },
      { title: 'Salve a unidade', description: 'Clique em Salvar Filial. Confira nome, CNPJ, endereço e status no cartão de Filiais Registradas.' },
      { title: 'Faça a manutenção', description: 'Use o ícone Editar Dados da Filial para corrigir informações. Use Inativar Filial ou Ativar Filial para mudar a disponibilidade e confira o status retornado.' },
    ],
    verification: ['A filial aparece vinculada à matriz correta, com seu próprio CNPJ.', 'A unidade está disponível no seletor Unidade configurada da aba Rotinas e Obrigações.'],
    related: ['parceiros-obrigacoes'],
  },
  {
    id: 'parceiros-obrigacoes', title: 'Definir obrigações da matriz e de cada filial',
    summary: 'Selecione quais obrigações se aplicam a cada unidade do cliente antes de trabalhar nas rotinas.',
    path: 'Parceiros → cliente contábil → Rotinas e Obrigações',
    prerequisites: ['Parceiro classificado como Cliente Contábil.', 'Obrigações ativas cadastradas e aplicáveis ao regime da unidade.'],
    steps: [
      { title: 'Abra a configuração', description: 'No detalhe do cliente, entre em Rotinas e Obrigações e aguarde o carregamento.' },
      { title: 'Escolha a unidade', description: 'Em Unidade configurada, selecione Matriz ou a Filial desejada. Confira o nome e o tipo de estabelecimento no resumo.' },
      { title: 'Selecione as obrigações', description: 'Clique em Adicionar obrigações ou Editar obrigações. Marque somente os itens aplicáveis; a seleção é agrupada por categoria.' },
      { title: 'Grave a seleção', description: 'Confira a contagem e clique em Salvar seleção. Aguarde a mensagem Obrigações sincronizadas. Cancelar descarta a seleção ainda não salva.' },
      { title: 'Confira os detalhes', description: 'Na lista resultante, revise periodicidade, prazo, origem e Etapas. Essas informações vêm do cadastro da obrigação em Parametrização.' },
      { title: 'Configure as demais unidades', description: 'Depois de salvar, troque Unidade configurada e repita o processo para cada filial. Cada unidade mantém sua própria seleção.' },
      { title: 'Continue nas rotinas', description: 'Clique em Abrir rotinas para acessar Rotinas com o contexto da unidade selecionada e seguir a geração e organização das atividades.' },
    ],
    verification: ['A quantidade e os nomes exibidos correspondem à seleção salva para aquela unidade.', 'Ao trocar e retornar à unidade, as obrigações configuradas permanecem selecionadas.'],
    tips: ['Se não houver obrigação disponível, confira status e regimes aplicáveis em Parametrização → Obrigações.', 'Se a configuração tiver mudado em outra tela, clique em Recarregar configuração e revise a seleção antes de salvar novamente.', 'Salvar a seleção define as obrigações aplicáveis. A execução das tarefas é acompanhada em Atividades e Acompanhamento.'],
    related: ['param-obrigacoes', 'param-obrigacoes-prazos'],
  },
  {
    id: 'parceiros-excluir', title: 'Inativar ou excluir um parceiro da carteira',
    summary: 'Entenda as opções para deixar de usar um cadastro e a proteção aplicada quando ele possui arquivos.',
    path: 'Parceiros → visualização em cartões → ações do parceiro',
    prerequisites: ['Identificar pelo CPF/CNPJ o cadastro que deixará de ser utilizado.', 'Definir se o cadastro deve permanecer disponível como inativo.'],
    steps: [
      { title: 'Localize o cadastro', description: 'Abra Parceiros, pesquise o parceiro e use a visualização em cartões. Confira o documento antes de acionar os ícones do cartão.' },
      { title: 'Inative quando quiser manter o cadastro', description: 'Use Inativar parceiro no cartão. Depois procure o parceiro na aba Inativos; o ícone Ativar parceiro permite disponibilizá-lo novamente.' },
      { title: 'Inicie a exclusão quando aplicável', description: 'Se a intenção for excluir o cadastro, clique no ícone Excluir parceiro. O sistema verifica a existência de arquivos vinculados antes de oferecer a confirmação.' },
      { title: 'Leia a mensagem exibida', description: 'Em Excluir Parceiro, confira o nome e a informação sobre remoção das pastas vazias; use Excluir para concluir ou Cancelar para desistir. Se aparecer Parceiro com arquivos, a exclusão está bloqueada e a tela oferece Inativar parceiro.' },
      { title: 'Confira o resultado', description: 'Após inativar, confira a aba Inativos. Após excluir, refaça a busca e confira a mensagem de resultado; se houver erro, leia o motivo antes de repetir.' },
    ],
    verification: ['O parceiro aparece em Inativos quando essa foi a operação escolhida.', 'Na exclusão concluída, o parceiro deixa de aparecer na carteira.'],
    tips: ['A exclusão confirmada também remove as pastas e subpastas vazias do parceiro. A ação com arquivos vinculados possui um bloqueio próprio.'],
    related: ['parceiros-localizar', 'parceiros-editar'],
  },
];
