export type MotivationalPhrase = {
  texto: string;
  autor: string;
  categoria?: string;
};

const fontes = [
  { autor: 'Inspirado em Sêneca', categoria: 'sabedoria', texto: 'A dificuldade não veio para provar que você é fraco, mas para revelar a força que ainda não tinha sido chamada.' },
  { autor: 'Inspirado em Marco Aurélio', categoria: 'disciplina', texto: 'Você tem poder sobre a forma como responde ao dia; comece por aí e o restante fica mais leve.' },
  { autor: 'Inspirado em Aristóteles', categoria: 'disciplina', texto: 'Excelência não nasce de um momento de empolgação, mas de pequenos hábitos bem escolhidos e repetidos com firmeza.' },
  { autor: 'Inspirado em Sócrates', categoria: 'reflexao', texto: 'Conhecer a si mesmo também é perceber quando precisa recomeçar com mais calma, mais verdade e menos cobrança.' },
  { autor: 'Inspirado em Confúcio', categoria: 'perseveranca', texto: 'Não importa ir devagar; importa não abandonar a direção que pode transformar sua vida.' },
  { autor: 'Inspirado em Lao Tsé', categoria: 'paz', texto: 'O caminho grande começa simples, com um passo honesto dado apesar do cansaço.' },
  { autor: 'Inspirado em Nelson Mandela', categoria: 'coragem', texto: 'O impossível costuma parecer definitivo até alguém cansado, mas decidido, atravessar a primeira porta.' },
  { autor: 'Inspirado em Maya Angelou', categoria: 'forca', texto: 'Você pode não controlar tudo que acontece, mas pode preservar a dignidade com que se levanta.' },
  { autor: 'Inspirado em Martin Luther King Jr.', categoria: 'esperanca', texto: 'Dê o primeiro passo mesmo sem enxergar a escada inteira; a coragem também aprende andando.' },
  { autor: 'Inspirado em Winston Churchill', categoria: 'perseveranca', texto: 'Sucesso é continuar depois de dias difíceis, sem deixar que uma queda escreva o final da história.' },
  { autor: 'Inspirado em Theodore Roosevelt', categoria: 'confianca', texto: 'Acredite que você pode avançar; metade da caminhada começa quando a mente para de desistir antes do corpo.' },
  { autor: 'Inspirado em Henry Ford', categoria: 'confianca', texto: 'Se você acredita que consegue melhorar, já abriu espaço para a ação provar que era possível.' },
  { autor: 'Inspirado em Thomas Edison', categoria: 'resiliencia', texto: 'Cada tentativa que não funcionou ensinou algo; não desperdice a lição chamando-a apenas de fracasso.' },
  { autor: 'Inspirado em Albert Einstein', categoria: 'reflexao', texto: 'No meio da dificuldade também existe uma oportunidade escondida, esperando sua mente respirar para enxergá-la.' },
  { autor: 'Inspirado em Viktor Frankl', categoria: 'proposito', texto: 'Quando você reencontra um sentido, até o sofrimento perde parte do poder de paralisar seus passos.' },
  { autor: 'Inspirado em C.S. Lewis', categoria: 'recomeco', texto: 'Você nunca é velho demais, nem está atrasado demais, para escolher um novo começo com esperança.' },
  { autor: 'Inspirado em Napoleon Hill', categoria: 'disciplina', texto: 'A meta fica mais próxima quando desejo, plano e ação começam a caminhar na mesma direção.' },
  { autor: 'Inspirado em Jim Rohn', categoria: 'disciplina', texto: 'Disciplina é a ponte discreta entre o que você sonha e o que decide construir hoje.' },
  { autor: 'Inspirado em Zig Ziglar', categoria: 'animo', texto: 'A motivação precisa ser renovada, e tudo bem: algumas forças bonitas também são cultivadas diariamente.' },
  { autor: 'Inspirado em Dale Carnegie', categoria: 'paz', texto: 'Viva este dia com presença; carregar todos os problemas de uma vez só torna qualquer coração pesado demais.' },
  { autor: 'Inspirado em Peter Drucker', categoria: 'proposito', texto: 'O melhor jeito de preparar o futuro é fazer com clareza aquilo que está sob sua responsabilidade agora.' },
  { autor: 'Inspirado em Stephen Covey', categoria: 'sabedoria', texto: 'Comece pelo que é essencial; quando os valores lideram, as tarefas deixam de mandar na sua paz.' },
  { autor: 'Inspirado em Warren Buffett', categoria: 'sabedoria', texto: 'Invista em você com paciência; conhecimento, caráter e constância rendem frutos que crise nenhuma toma facilmente.' },
  { autor: 'Inspirado em Steve Jobs', categoria: 'proposito', texto: 'Faça um trabalho que tenha significado para você; a energia muda quando existe propósito por trás do esforço.' },
  { autor: 'Inspirado em Oprah Winfrey', categoria: 'gratidao', texto: 'Reconheça o que já existe de bom; gratidão não nega a luta, apenas devolve equilíbrio ao olhar.' },
  { autor: 'Inspirado em Brené Brown', categoria: 'coragem', texto: 'Coragem também é aparecer de coração aberto, mesmo quando a insegurança tenta mandar você se esconder.' },
  { autor: 'Inspirado em Tony Robbins', categoria: 'animo', texto: 'Uma decisão verdadeira pode mudar o ritmo do dia; escolha agir antes que o medo escolha por você.' },
  { autor: 'Inspirado em Les Brown', categoria: 'esperanca', texto: 'Mire alto sem desprezar o começo; sonhos grandes também precisam de passos pequenos e consistentes.' },
  { autor: 'Inspirado em John Maxwell', categoria: 'lideranca', texto: 'Liderar a própria vida começa quando você assume responsabilidade pelo próximo passo, não pelo mundo inteiro.' },
  { autor: 'Inspirado em Ayrton Senna', categoria: 'vitoria', texto: 'Quando existe dedicação verdadeira, o limite de ontem vira apenas uma marca a ser superada com respeito.' },
  { autor: 'Inspirado em Pelé', categoria: 'disciplina', texto: 'Talento ajuda, mas treino, humildade e repetição transformam potencial em resultado que permanece.' },
  { autor: 'Inspirado em Muhammad Ali', categoria: 'confianca', texto: 'A vitória começa na mente antes de aparecer do lado de fora; fale consigo como quem acredita.' },
  { autor: 'Inspirado em Michael Jordan', categoria: 'resiliencia', texto: 'Você pode errar muitas vezes e ainda assim vencer, desde que não transforme erro em desistência.' },
  { autor: 'Inspirado em Kobe Bryant', categoria: 'disciplina', texto: 'Compromisso é fazer o necessário mesmo quando ninguém vê, ninguém aplaude e o ânimo está baixo.' },
  { autor: 'Inspirado em Serena Williams', categoria: 'forca', texto: 'Força também é entrar no dia com foco, apesar das dúvidas que tentam diminuir sua presença.' },
  { autor: 'Inspirado em Madre Teresa de Calcutá', categoria: 'proposito', texto: 'Nem sempre dá para fazer algo grande, mas sempre é possível fazer algo pequeno com amor.' },
  { autor: 'Inspirado em Papa Francisco', categoria: 'esperanca', texto: 'A esperança abre janelas onde o medo só consegue enxergar paredes.' },
  { autor: 'Inspirado em Clarice Lispector', categoria: 'recomeco', texto: 'Permita-se nascer de novo dentro do mesmo dia; às vezes a alma só precisa de uma chance sincera.' },
  { autor: 'Inspirado em Machado de Assis', categoria: 'reflexao', texto: 'Olhe a vida com lucidez, mas não deixe que a lucidez roube sua capacidade de acreditar.' },
  { autor: 'Inspirado em Carlos Drummond de Andrade', categoria: 'perseveranca', texto: 'Havia uma pedra no caminho, mas também havia caminho depois da pedra.' },
  { autor: 'Inspirado em Cecília Meireles', categoria: 'paz', texto: 'Aprenda a guardar beleza mesmo nos dias incertos; ela ajuda a alma a não endurecer.' },
  { autor: 'Inspirado em Fernando Pessoa', categoria: 'coragem', texto: 'Tudo vale a pena quando a alma encontra sentido para continuar atravessando o mar.' },
  { autor: 'Inspirado em Paulo Freire', categoria: 'esperanca', texto: 'Esperança não é espera parada; é força que se levanta para transformar a realidade.' },
  { autor: 'Inspirado em Rubem Alves', categoria: 'leveza', texto: 'Há sabedoria em cuidar da alegria; ela também ensina a caminhar em dias pesados.' },
  { autor: 'Inspirado em Augusto Cury', categoria: 'autocuidado', texto: 'Gerencie seus pensamentos com carinho; nem toda voz dentro da mente merece virar verdade.' },
  { autor: 'Inspirado em Mario Sergio Cortella', categoria: 'proposito', texto: 'Faça o melhor possível nas condições que você tem, enquanto trabalha para melhorar essas condições.' },
  { autor: 'Inspirado em Leandro Karnal', categoria: 'reflexao', texto: 'Maturidade é perceber que nem todo desconforto é inimigo; alguns desconfortos educam a alma.' },
  { autor: 'Inspirado em Abraham Lincoln', categoria: 'integridade', texto: 'A melhor forma de prever quem você será é construir, hoje, uma atitude da qual possa se orgulhar.' },
  { autor: 'Inspirado em Benjamin Franklin', categoria: 'disciplina', texto: 'Pequenas economias de tempo, atenção e energia constroem grandes reservas de futuro.' },
  { autor: 'Inspirado em Helen Keller', categoria: 'esperanca', texto: 'Mesmo quando a visão falha, a esperança consegue apontar uma direção para o coração.' },
  { autor: 'Inspirado em Anne Frank', categoria: 'luz', texto: 'Ainda existe bondade para procurar, cultivar e proteger, mesmo quando o mundo parece difícil demais.' },
  { autor: 'Inspirado em Mahatma Gandhi', categoria: 'paz', texto: 'Seja no cotidiano a mudança que você espera encontrar no caminho.' },
  { autor: 'Inspirado em Desmond Tutu', categoria: 'esperanca', texto: 'A esperança é teimosa: ela insiste em procurar luz mesmo quando a sala parece escura.' },
  { autor: 'Inspirado em Dalai Lama', categoria: 'paz', texto: 'Uma mente mais calma não resolve tudo, mas enxerga melhor o próximo passo.' },
  { autor: 'Inspirado em Provérbio Japonês', categoria: 'resiliencia', texto: 'Caia sete vezes, levante oito; a dignidade está em voltar mais uma vez.' },
  { autor: 'Inspirado em Provérbio Africano', categoria: 'forca', texto: 'Se quiser ir longe, valorize quem caminha com você e fortaleça bons vínculos.' },
  { autor: 'Inspirado em Provérbio Chinês', categoria: 'perseveranca', texto: 'Quem move uma montanha começa carregando pequenas pedras; não despreze o começo.' },
  { autor: 'Salmo 23:4 (paráfrase)', categoria: 'fe', texto: 'Mesmo em vale difícil, você não caminha sem amparo; há presença, consolo e direção.' },
  { autor: 'Salmo 46:1 (paráfrase)', categoria: 'fe', texto: 'Na aflição, existe refúgio; você pode respirar antes de tentar carregar tudo sozinho.' },
  { autor: 'Isaías 41:10 (paráfrase)', categoria: 'fe', texto: 'Não tema: há força sendo renovada em você quando a sua parece pequena demais.' },
];

const reforcos = [
  'Respire fundo, organize uma prioridade e dê a si mesmo a chance de vencer o dia em partes.',
  'Hoje não precisa ser perfeito; precisa apenas ter um gesto honesto de continuidade.',
  'A fase difícil pode até diminuir seu ritmo, mas não precisa apagar sua direção.',
  'Você já superou dias que pareciam maiores do que suas forças; lembre-se disso agora.',
  'Escolha uma atitude pequena, concreta e boa; muitas viradas começam sem barulho.',
  'Trate-se com respeito enquanto luta, porque coragem também precisa de cuidado.',
  'O próximo passo vale mais do que a culpa por tudo que ainda não foi feito.',
];

export const frasesMotivacionaisData: MotivationalPhrase[] = fontes.flatMap((fonte) =>
  reforcos.map((reforco) => ({
    texto: `${fonte.texto} ${reforco}`,
    autor: fonte.autor,
    categoria: fonte.categoria,
  }))
);
