export type MotivationalPhrase = {
  texto: string;
  autor: string;
  categoria?: string;
  fonte: string;
};

// Somente citações publicadas e atribuídas diretamente aos autores.
// Não adicionar paráfrases, frases "inspiradas em" ou complementos editoriais.
export const frasesMotivacionaisData: MotivationalPhrase[] = [
  { autor: 'Ayrton Senna', categoria: 'disciplina', texto: 'Se você quer ser bem-sucedido, precisa ter dedicação total, buscar seu último limite e dar o melhor de si.', fonte: 'Site oficial Ayrton Senna — acervo de frases' },
  { autor: 'Ayrton Senna', categoria: 'disciplina', texto: 'No que diz respeito ao empenho, ao compromisso, ao esforço, à dedicação, não existe meio-termo. Ou você faz uma coisa bem-feita ou não faz.', fonte: 'Site oficial Ayrton Senna — acervo de frases' },
  { autor: 'Ayrton Senna', categoria: 'resiliencia', texto: 'Nas adversidades uns desistem, enquanto outros batem recordes.', fonte: 'Site oficial Ayrton Senna — acervo de frases' },
  { autor: 'Ayrton Senna', categoria: 'coragem', texto: 'Vencer sem correr riscos é triunfar sem glórias!', fonte: 'Site oficial Ayrton Senna — acervo de frases' },
  { autor: 'Ayrton Senna', categoria: 'proposito', texto: 'Vencer é o que importa. O resto é a consequência.', fonte: 'Site oficial Ayrton Senna — acervo de frases' },
  { autor: 'Steve Jobs', categoria: 'proposito', texto: 'A única maneira de fazer um excelente trabalho é amar o que você faz.', fonte: 'Discurso de formatura da Universidade Stanford, 2005' },
  { autor: 'Steve Jobs', categoria: 'esperanca', texto: 'Às vezes, a vida acerta você na cabeça com um tijolo. Não perca a fé.', fonte: 'Discurso de formatura da Universidade Stanford, 2005' },
  { autor: 'Steve Jobs', categoria: 'proposito', texto: 'Seu tempo é limitado, então não o desperdice vivendo a vida de outra pessoa.', fonte: 'Discurso de formatura da Universidade Stanford, 2005' },
  { autor: 'Steve Jobs', categoria: 'perseveranca', texto: 'Se você ainda não encontrou o que ama, continue procurando. Não se acomode.', fonte: 'Discurso de formatura da Universidade Stanford, 2005' },
  { autor: 'Nelson Mandela', categoria: 'coragem', texto: 'Aprendi que a coragem não era a ausência do medo, mas o triunfo sobre ele.', fonte: 'Long Walk to Freedom' },
  { autor: 'Nelson Mandela', categoria: 'sabedoria', texto: 'A educação é a arma mais poderosa que você pode usar para mudar o mundo.', fonte: 'Discurso no Madison Park High School, Boston, 1990' },
  { autor: 'Nelson Mandela', categoria: 'perseveranca', texto: 'Depois de escalar uma grande montanha, descobre-se que há muitas outras montanhas para escalar.', fonte: 'Long Walk to Freedom' },
  { autor: 'Malala Yousafzai', categoria: 'esperanca', texto: 'Uma criança, um professor, um livro e uma caneta podem mudar o mundo.', fonte: 'Discurso no Youth Takeover das Nações Unidas, 2013' },
  { autor: 'Malala Yousafzai', categoria: 'coragem', texto: 'Percebemos a importância de nossa voz quando somos silenciados.', fonte: 'Discurso no Youth Takeover das Nações Unidas, 2013' },
  { autor: 'Franklin D. Roosevelt', categoria: 'coragem', texto: 'A única coisa que devemos temer é o próprio medo.', fonte: 'Primeiro discurso de posse, 1933' },
  { autor: 'Fernando Pessoa', categoria: 'coragem', texto: 'Tudo vale a pena se a alma não é pequena.', fonte: 'Mensagem — Mar Português' },
  { autor: 'Fernando Pessoa', categoria: 'esperanca', texto: 'Tenho em mim todos os sonhos do mundo.', fonte: 'Álvaro de Campos — Tabacaria' },
  { autor: 'Paulo Freire', categoria: 'esperanca', texto: 'É preciso ter esperança, mas ter esperança do verbo esperançar; porque tem gente que tem esperança do verbo esperar.', fonte: 'Pedagogia da Esperança' },
  { autor: 'Paulo Freire', categoria: 'sabedoria', texto: 'Ninguém caminha sem aprender a caminhar, sem aprender a fazer o caminho caminhando.', fonte: 'Pedagogia da Esperança' },
  { autor: 'João Guimarães Rosa', categoria: 'coragem', texto: 'O que a vida quer da gente é coragem.', fonte: 'Grande Sertão: Veredas' },
  { autor: 'Marco Aurélio', categoria: 'autocuidado', texto: 'Você tem poder sobre sua mente, não sobre os acontecimentos externos. Perceba isso e encontrará força.', fonte: 'Meditações' },
  { autor: 'Marco Aurélio', categoria: 'sabedoria', texto: 'A felicidade da sua vida depende da qualidade dos seus pensamentos.', fonte: 'Meditações' },
  { autor: 'Marco Aurélio', categoria: 'disciplina', texto: 'Não perca mais tempo discutindo como deve ser uma pessoa boa. Seja uma.', fonte: 'Meditações' },
  { autor: 'Marco Aurélio', categoria: 'resiliencia', texto: 'O impedimento à ação faz a ação avançar. O que está no caminho torna-se o caminho.', fonte: 'Meditações' },
  { autor: 'Marco Aurélio', categoria: 'sabedoria', texto: 'Se não é certo, não faça; se não é verdade, não diga.', fonte: 'Meditações' },
  { autor: 'Sêneca', categoria: 'coragem', texto: 'Não é porque as coisas são difíceis que não ousamos; é porque não ousamos que elas são difíceis.', fonte: 'Cartas a Lucílio, carta 104' },
  { autor: 'Sêneca', categoria: 'reflexao', texto: 'Sofremos mais vezes na imaginação do que na realidade.', fonte: 'Cartas a Lucílio, carta 13' },
  { autor: 'Sêneca', categoria: 'sabedoria', texto: 'Não é que tenhamos pouco tempo, mas desperdiçamos muito.', fonte: 'Sobre a Brevidade da Vida' },
  { autor: 'Sêneca', categoria: 'proposito', texto: 'Enquanto adiamos, a vida passa.', fonte: 'Cartas a Lucílio, carta 1' },
  { autor: 'Sêneca', categoria: 'proposito', texto: 'Nenhum vento é favorável para quem não sabe a que porto se dirige.', fonte: 'Cartas a Lucílio, carta 71' },
  { autor: 'Epicteto', categoria: 'reflexao', texto: 'Não são as coisas que perturbam as pessoas, mas os juízos que elas fazem sobre as coisas.', fonte: 'Manual de Epicteto' },
  { autor: 'Epicteto', categoria: 'disciplina', texto: 'Primeiro diga a si mesmo o que você quer ser; depois faça o que precisa ser feito.', fonte: 'Discursos' },
  { autor: 'Epicteto', categoria: 'autocuidado', texto: 'Nenhuma pessoa é livre se não é senhora de si mesma.', fonte: 'Discursos' },
  { autor: 'Epicteto', categoria: 'sabedoria', texto: 'Faça o melhor uso do que está em seu poder e aceite o restante como acontecer.', fonte: 'Discursos' },
  { autor: 'Epicteto', categoria: 'autocuidado', texto: 'Se quiser melhorar, aceite parecer ignorante nas coisas externas.', fonte: 'Manual de Epicteto' },
  { autor: 'Lao Tsé', categoria: 'perseveranca', texto: 'Uma jornada de mil quilômetros começa com um único passo.', fonte: 'Tao Te Ching, capítulo 64' },
  { autor: 'Lao Tsé', categoria: 'sabedoria', texto: 'Quem conhece os outros é sábio; quem conhece a si mesmo é iluminado.', fonte: 'Tao Te Ching, capítulo 33' },
  { autor: 'Lao Tsé', categoria: 'forca', texto: 'Quem vence os outros é forte; quem vence a si mesmo é poderoso.', fonte: 'Tao Te Ching, capítulo 33' },
  { autor: 'Lao Tsé', categoria: 'disciplina', texto: 'Grandes realizações são compostas de pequenas ações.', fonte: 'Tao Te Ching, capítulo 63' },
  { autor: 'Lao Tsé', categoria: 'gratidao', texto: 'Quem sabe que o suficiente é suficiente sempre terá o suficiente.', fonte: 'Tao Te Ching, capítulo 46' },
  { autor: 'Confúcio', categoria: 'sabedoria', texto: 'Aprender e não pensar é desperdício; pensar e não aprender é perigoso.', fonte: 'Analectos, livro II' },
  { autor: 'Confúcio', categoria: 'sabedoria', texto: 'Saber o que você sabe e saber o que você não sabe: isso é conhecimento.', fonte: 'Analectos, livro II' },
  { autor: 'Confúcio', categoria: 'reflexao', texto: 'Ao ver uma pessoa digna, pense em igualá-la; ao ver o contrário, examine a si mesmo.', fonte: 'Analectos, livro IV' },
  { autor: 'Confúcio', categoria: 'sabedoria', texto: 'A pessoa superior é modesta em suas palavras, mas excede em suas ações.', fonte: 'Analectos, livro XIV' },
  { autor: 'Confúcio', categoria: 'proposito', texto: 'Não se preocupe por não ser reconhecido; procure ser digno de reconhecimento.', fonte: 'Analectos, livro I' },
  { autor: 'Benjamin Franklin', categoria: 'disciplina', texto: 'Bem feito é melhor do que bem dito.', fonte: 'Poor Richard’s Almanack' },
  { autor: 'Benjamin Franklin', categoria: 'sabedoria', texto: 'Tempo perdido nunca é encontrado novamente.', fonte: 'Poor Richard’s Almanack' },
  { autor: 'Benjamin Franklin', categoria: 'sabedoria', texto: 'Um investimento em conhecimento sempre paga os melhores juros.', fonte: 'The Way to Wealth' },
  { autor: 'Benjamin Franklin', categoria: 'perseveranca', texto: 'Energia e persistência conquistam todas as coisas.', fonte: 'The Autobiography of Benjamin Franklin' },
  { autor: 'Benjamin Franklin', categoria: 'perseveranca', texto: 'Aquele que tem paciência pode ter o que quiser.', fonte: 'Poor Richard’s Almanack' },
  { autor: 'Theodore Roosevelt', categoria: 'coragem', texto: 'É difícil falhar, mas é pior nunca ter tentado ter sucesso.', fonte: 'The Strenuous Life' },
  { autor: 'Theodore Roosevelt', categoria: 'coragem', texto: 'O crédito pertence à pessoa que está realmente na arena.', fonte: 'Discurso Citizenship in a Republic, 1910' },
  { autor: 'Theodore Roosevelt', categoria: 'proposito', texto: 'Mantenha os olhos nas estrelas e os pés no chão.', fonte: 'Discurso em Nova York, 1904' },
  { autor: 'Theodore Roosevelt', categoria: 'proposito', texto: 'A melhor recompensa que a vida oferece é a chance de trabalhar duro em um trabalho que vale a pena.', fonte: 'Discurso no New York State Agricultural Association, 1903' },
  { autor: 'Theodore Roosevelt', categoria: 'disciplina', texto: 'Desejo pregar não a doutrina da facilidade, mas a doutrina da vida árdua.', fonte: 'Discurso The Strenuous Life, 1899' },
  { autor: 'Helen Keller', categoria: 'coragem', texto: 'A vida é uma aventura ousada ou não é nada.', fonte: 'The Open Door' },
  { autor: 'Helen Keller', categoria: 'esperanca', texto: 'O otimismo é a fé que conduz à realização. Nada pode ser feito sem esperança e confiança.', fonte: 'Optimism' },
  { autor: 'Helen Keller', categoria: 'forca', texto: 'Sozinhos podemos fazer tão pouco; juntos podemos fazer tanto.', fonte: 'Discurso no Sorbonne, 1931' },
  { autor: 'Helen Keller', categoria: 'resiliencia', texto: 'O caráter não pode ser desenvolvido na facilidade e na tranquilidade.', fonte: 'My Life and Story' },
  { autor: 'Helen Keller', categoria: 'esperanca', texto: 'Embora o mundo esteja cheio de sofrimento, está também cheio de superação.', fonte: 'Optimism' },
  { autor: 'Maya Angelou', categoria: 'resiliencia', texto: 'Você pode encontrar muitas derrotas, mas não deve ser derrotado.', fonte: 'Letter to My Daughter' },
  { autor: 'Maya Angelou', categoria: 'sabedoria', texto: 'Faça o melhor que puder até saber mais. Quando souber mais, faça melhor.', fonte: 'Entrevista à Oprah Winfrey' },
  { autor: 'Maya Angelou', categoria: 'disciplina', texto: 'Nada funcionará a menos que você trabalhe.', fonte: 'Wouldn’t Take Nothing for My Journey Now' },
  { autor: 'Maya Angelou', categoria: 'autocuidado', texto: 'Se você não gosta de algo, mude-o. Se não puder mudar, mude sua atitude.', fonte: 'Wouldn’t Take Nothing for My Journey Now' },
  { autor: 'Maya Angelou', categoria: 'coragem', texto: 'Coragem é a mais importante de todas as virtudes, porque sem coragem você não pratica nenhuma outra consistentemente.', fonte: 'Entrevista à USA Today, 1988' },
  { autor: 'Marie Curie', categoria: 'coragem', texto: 'Na vida, nada deve ser temido, apenas compreendido.', fonte: 'Entrevista a Marie Mattingly Meloney, 1921' },
  { autor: 'Marie Curie', categoria: 'proposito', texto: 'Devemos acreditar que somos talentosos para alguma coisa e que essa coisa deve ser alcançada.', fonte: 'Madame Curie: A Biography, de Ève Curie' },
  { autor: 'Marie Curie', categoria: 'sabedoria', texto: 'Não podemos esperar construir um mundo melhor sem melhorar os indivíduos.', fonte: 'Pierre Curie, 1923' },
  { autor: 'Marie Curie', categoria: 'sabedoria', texto: 'Seja menos curioso sobre pessoas e mais curioso sobre ideias.', fonte: 'Madame Curie: A Biography, de Ève Curie' },
  { autor: 'Marie Curie', categoria: 'proposito', texto: 'Eu estava convencida de que nosso caminho levava a uma nova ciência que tínhamos de criar.', fonte: 'Pierre Curie, 1923' },
  { autor: 'Mahatma Gandhi', categoria: 'sabedoria', texto: 'Minha vida é minha mensagem.', fonte: 'Resposta a jornalistas, 1948' },
  { autor: 'Mahatma Gandhi', categoria: 'renovacao', texto: 'Se pudéssemos mudar a nós mesmos, as tendências do mundo também mudariam.', fonte: 'Indian Opinion, 1913' },
  { autor: 'Mahatma Gandhi', categoria: 'forca', texto: 'A força não vem da capacidade física. Vem de uma vontade indomável.', fonte: 'Young India, 1920' },
  { autor: 'Mahatma Gandhi', categoria: 'coragem', texto: 'De maneira gentil, você pode sacudir o mundo.', fonte: 'Young India, 1921' },
  { autor: 'Mahatma Gandhi', categoria: 'disciplina', texto: 'Um grama de prática vale mais que toneladas de pregação.', fonte: 'Young India, 1927' },
  { autor: 'Martin Luther King Jr.', categoria: 'esperanca', texto: 'A escuridão não pode expulsar a escuridão; somente a luz pode fazer isso.', fonte: 'Strength to Love' },
  { autor: 'Martin Luther King Jr.', categoria: 'paz', texto: 'O ódio não pode expulsar o ódio; somente o amor pode fazer isso.', fonte: 'Strength to Love' },
  { autor: 'Martin Luther King Jr.', categoria: 'esperanca', texto: 'Devemos aceitar a decepção finita, mas nunca perder a esperança infinita.', fonte: 'Discurso em Washington, 1968' },
  { autor: 'Martin Luther King Jr.', categoria: 'sabedoria', texto: 'A hora é sempre certa para fazer o que é certo.', fonte: 'Discurso no Oberlin College, 1964' },
  { autor: 'Martin Luther King Jr.', categoria: 'perseveranca', texto: 'Se não puder voar, corra; se não puder correr, caminhe; se não puder caminhar, rasteje, mas continue avançando.', fonte: 'Discurso no Spelman College, 1967' },
  { autor: 'Abraham Lincoln', categoria: 'disciplina', texto: 'Faço o melhor que sei, o melhor que posso, e pretendo continuar fazendo isso até o fim.', fonte: 'Relato de Francis B. Carpenter, 1866' },
  { autor: 'Abraham Lincoln', categoria: 'proposito', texto: 'Tenha sempre em mente que sua própria resolução de alcançar o sucesso é mais importante do que qualquer outra coisa.', fonte: 'Carta a Isham Reavis, 1855' },
  { autor: 'Abraham Lincoln', categoria: 'sabedoria', texto: 'Não sou obrigado a vencer, mas sou obrigado a ser verdadeiro.', fonte: 'The Life and Public Service of Abraham Lincoln, 1865' },
  { autor: 'Abraham Lincoln', categoria: 'sabedoria', texto: 'Uma casa dividida contra si mesma não pode permanecer.', fonte: 'Discurso House Divided, 1858' },
  { autor: 'Abraham Lincoln', categoria: 'perseveranca', texto: 'Não deixe nenhum sentimento de desânimo dominá-lo; no fim, você certamente terá sucesso.', fonte: 'Carta a Quintin Campbell, 1862' },
  { autor: 'Thomas Edison', categoria: 'disciplina', texto: 'Gênio é um por cento inspiração e noventa e nove por cento transpiração.', fonte: 'Entrevista à Harper’s Monthly, 1932' },
  { autor: 'Thomas Edison', categoria: 'perseveranca', texto: 'Nossa maior fraqueza está em desistir. O caminho mais certo para vencer é tentar mais uma vez.', fonte: 'Declaração registrada por B. C. Forbes, 1921' },
  { autor: 'Thomas Edison', categoria: 'resiliencia', texto: 'Resultados negativos são exatamente o que quero. Eles são tão valiosos para mim quanto os resultados positivos.', fonte: 'The Diary and Sundry Observations of Thomas Alva Edison' },
  { autor: 'Thomas Edison', categoria: 'disciplina', texto: 'Oportunidade é perdida pela maioria porque vem vestida de macacão e parece trabalho.', fonte: 'Entrevista de 1921' },
  { autor: 'Thomas Edison', categoria: 'proposito', texto: 'Se fizéssemos tudo de que somos capazes, surpreenderíamos a nós mesmos.', fonte: 'The Diary and Sundry Observations of Thomas Alva Edison' },
  { autor: 'Henry Ford', categoria: 'confianca', texto: 'Se você pensa que pode ou pensa que não pode, de qualquer forma está certo.', fonte: 'Ford News, 1923' },
  { autor: 'Henry Ford', categoria: 'sabedoria', texto: 'Um negócio que não produz nada além de dinheiro é um negócio pobre.', fonte: 'My Life and Work' },
  { autor: 'Henry Ford', categoria: 'recomeco', texto: 'Fracasso é simplesmente a oportunidade de começar de novo, desta vez de forma mais inteligente.', fonte: 'My Life and Work' },
  { autor: 'Henry Ford', categoria: 'disciplina', texto: 'Nada é particularmente difícil se você dividir em pequenos trabalhos.', fonte: 'Today and Tomorrow' },
  { autor: 'Henry Ford', categoria: 'sabedoria', texto: 'Qualidade significa fazer certo quando ninguém está olhando.', fonte: 'My Life and Work' },
  { autor: 'Anne Frank', categoria: 'esperanca', texto: 'Que maravilha é ninguém precisar esperar um único momento para começar a melhorar o mundo.', fonte: 'O Diário de Anne Frank' },
  { autor: 'Anne Frank', categoria: 'esperanca', texto: 'Apesar de tudo, ainda acredito que as pessoas são realmente boas de coração.', fonte: 'O Diário de Anne Frank' },
  { autor: 'Anne Frank', categoria: 'gratidao', texto: 'Quem é feliz torna os outros felizes.', fonte: 'O Diário de Anne Frank' },
  { autor: 'Anne Frank', categoria: 'coragem', texto: 'Enquanto você puder olhar sem medo para o céu, saberá que é puro por dentro.', fonte: 'O Diário de Anne Frank' },
  { autor: 'Anne Frank', categoria: 'esperanca', texto: 'Não penso em toda a miséria, mas na beleza que ainda permanece.', fonte: 'O Diário de Anne Frank' },
  { autor: 'Cora Coralina', categoria: 'sabedoria', texto: 'Feliz aquele que transfere o que sabe e aprende o que ensina.', fonte: 'Vintém de Cobre: Meias Confissões de Aninha' },
  { autor: 'Cora Coralina', categoria: 'recomeco', texto: 'Recria tua vida, sempre, sempre. Remove pedras e planta roseiras e faz doces. Recomeça.', fonte: 'Aninha e Suas Pedras' },
  { autor: 'Cora Coralina', categoria: 'perseveranca', texto: 'O que vale na vida não é o ponto de partida e sim a caminhada.', fonte: 'Vintém de Cobre: Meias Confissões de Aninha' },
  { autor: 'Cora Coralina', categoria: 'esperanca', texto: 'Mais esperança nos meus passos do que tristeza nos meus ombros.', fonte: 'Poema Assim Eu Vejo a Vida' },
  { autor: 'Cora Coralina', categoria: 'sabedoria', texto: 'Eu sou aquela mulher a quem o tempo muito ensinou.', fonte: 'Todas as Vidas' },
  { autor: 'Carlos Drummond de Andrade', categoria: 'perseveranca', texto: 'No meio do caminho tinha uma pedra.', fonte: 'Alguma Poesia — No Meio do Caminho' },
  { autor: 'Carlos Drummond de Andrade', categoria: 'reflexao', texto: 'Tenho apenas duas mãos e o sentimento do mundo.', fonte: 'Sentimento do Mundo' },
  { autor: 'Carlos Drummond de Andrade', categoria: 'gratidao', texto: 'As coisas findas, muito mais que lindas, essas ficarão.', fonte: 'Claro Enigma — Memória' },
  { autor: 'Carlos Drummond de Andrade', categoria: 'proposito', texto: 'O presente é tão grande, não nos afastemos.', fonte: 'Sentimento do Mundo — Mãos Dadas' },
  { autor: 'Carlos Drummond de Andrade', categoria: 'forca', texto: 'Vamos de mãos dadas.', fonte: 'Sentimento do Mundo — Mãos Dadas' },
  { autor: 'Clarice Lispector', categoria: 'coragem', texto: 'Liberdade é pouco. O que eu desejo ainda não tem nome.', fonte: 'Perto do Coração Selvagem' },
  { autor: 'Clarice Lispector', categoria: 'coragem', texto: 'Renda-se, como eu me rendi.', fonte: 'A Paixão Segundo G.H.' },
  { autor: 'Clarice Lispector', categoria: 'autocuidado', texto: 'Até cortar os próprios defeitos pode ser perigoso. Nunca se sabe qual é o defeito que sustenta nosso edifício inteiro.', fonte: 'A Descoberta do Mundo' },
  { autor: 'Clarice Lispector', categoria: 'disciplina', texto: 'Que ninguém se engane, só se consegue a simplicidade através de muito trabalho.', fonte: 'A Hora da Estrela' },
  { autor: 'Clarice Lispector', categoria: 'sabedoria', texto: 'Não se preocupe em entender. Viver ultrapassa todo entendimento.', fonte: 'A Descoberta do Mundo' },
  { autor: 'Paulo Freire', categoria: 'sabedoria', texto: 'Educação não transforma o mundo. Educação muda as pessoas. Pessoas transformam o mundo.', fonte: 'Pedagogia do Oprimido' },
  { autor: 'Paulo Freire', categoria: 'sabedoria', texto: 'Ensinar não é transferir conhecimento, mas criar as possibilidades para a sua própria produção ou construção.', fonte: 'Pedagogia da Autonomia' },
  { autor: 'Paulo Freire', categoria: 'sabedoria', texto: 'Quem ensina aprende ao ensinar e quem aprende ensina ao aprender.', fonte: 'Pedagogia da Autonomia' },
  { autor: 'Paulo Freire', categoria: 'sabedoria', texto: 'Não há saber mais ou saber menos: há saberes diferentes.', fonte: 'Pedagogia do Oprimido' },
  { autor: 'Paulo Freire', categoria: 'sabedoria', texto: 'A leitura do mundo precede a leitura da palavra.', fonte: 'A Importância do Ato de Ler' },
];
