import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  actionBtn: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    border: '1px solid rgba(197, 146, 53, 0.4)',
    borderRadius: '6px',
    color: 'var(--color-gold-dark)',
    cursor: 'pointer',
    display: 'flex',
    fontSize: '0.8rem',
    fontWeight: 600,
    gap: '6px',
    padding: '8px 14px',
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    border: '1px solid #e2e8f0',
    borderRadius: '50%',
    color: 'var(--color-gold-dark)',
    display: 'flex',
    fontSize: '0.9rem',
    fontWeight: 700,
    height: '38px',
    justifyContent: 'center',
    width: '38px',
  },
  avatarBig: {
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    border: '1px solid #e2e8f0',
    borderRadius: '50%',
    color: 'var(--color-gold-dark)',
    display: 'flex',
    fontSize: '1.1rem',
    fontWeight: 700,
    height: '46px',
    justifyContent: 'center',
    width: '46px',
  },
  backBtn: {
    alignItems: 'center',
    background: 'none',
    border: 'none',
    color: '#64748b',
    cursor: 'pointer',
    display: 'flex',
    fontSize: '0.82rem',
    fontWeight: 500,
    gap: '4px',
  },
  companyActivityBox: {
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    padding: '12px',
  },
  detailChecklist: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    color: '#0f172a',
    display: 'flex',
    flexDirection: 'column',
    fontSize: '0.78rem',
    gap: '7px',
    minHeight: '46px',
    padding: '10px',
  },
  detailEyebrow: {
    color: 'var(--color-gold-dark)',
    fontSize: '0.68rem',
    fontWeight: 800,
    textTransform: 'uppercase',
  },
  detailMeta: {
    color: '#64748b',
    fontSize: '0.76rem',
    margin: '3px 0 0 0',
  },
  detailPanel: {
    backgroundColor: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    padding: '16px',
  },
  detailSectionLabel: {
    color: '#64748b',
    display: 'block',
    fontSize: '0.7rem',
    fontWeight: 900,
    marginBottom: '6px',
    textTransform: 'uppercase',
  },
  detailSplit: {
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: '1fr 1fr',
  },
  detailTitle: {
    color: '#0f172a',
    fontSize: '1rem',
    fontWeight: 800,
    margin: '3px 0 0 0',
  },
  emptyCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    border: '1px dashed #cbd5e1',
    borderRadius: '8px',
    display: 'flex',
    flexDirection: 'column',
    padding: '30px',
  },
  grid: {
    display: 'grid',
    gap: '16px',
    gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))',
  },
  inspectorGrid: {
    alignItems: 'start',
    display: 'grid',
    gap: '16px',
    gridTemplateColumns: 'minmax(320px, 0.95fr) minmax(360px, 1.05fr)',
  },
  manageBtn: {
    backgroundColor: 'transparent',
    border: '1px solid rgba(197, 146, 53, 0.4)',
    borderRadius: '6px',
    color: 'var(--color-gold-dark)',
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: 600,
    padding: '8px',
    textAlign: 'center',
    transition: 'all 0.2s',
  },
  notesGrid: {
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: '1fr 1fr',
  },
  openBtn: {
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    color: '#475569',
    cursor: 'pointer',
    display: 'inline-flex',
    fontSize: '0.74rem',
    fontWeight: 700,
    gap: '6px',
    padding: '6px 9px',
  },
  primaryBtn: {
    alignItems: 'center',
    background: 'linear-gradient(135deg, #c59235 0%, #aa7c28 100%)',
    border: 'none',
    borderRadius: '6px',
    boxShadow: '0 2px 6px rgba(197, 146, 53, 0.2)',
    color: '#ffffff',
    cursor: 'pointer',
    display: 'flex',
    fontSize: '0.8rem',
    fontWeight: 600,
    gap: '6px',
    padding: '8px 14px',
  },
  progressLine: {
    backgroundColor: '#f1f5f9',
    borderRadius: '999px',
    height: '7px',
    overflow: 'hidden',
  },
  segmented: {
    backgroundColor: '#f1f5f9',
    borderRadius: '6px',
    display: 'flex',
    padding: '3px',
  },
  segmentedItem: {
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontWeight: 600,
    padding: '6px 12px',
    transition: 'all 0.2s',
  },
  statusSelect: {
    backgroundColor: '#ffffff',
    border: '1px solid #cbd5e1',
    borderRadius: '4px',
    color: '#0f172a',
    cursor: 'pointer',
    fontSize: '0.75rem',
    outline: 'none',
    padding: '4px 8px',
  },
  summaryCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    color: '#64748b',
    display: 'grid',
    fontSize: '0.76rem',
    fontWeight: 700,
    gap: '8px',
    gridTemplateColumns: '24px 1fr auto',
    padding: '12px',
  },
  summaryGrid: {
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
  },
  taskCard: {
    backgroundColor: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    boxShadow: '0 1px 2px rgba(0,0,0,0.02)',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    padding: '14px',
  },
  toolbar: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    justifyContent: 'space-between',
    padding: '8px 16px',
  },
  userCard: {
    backgroundColor: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
    display: 'flex',
    flexDirection: 'column',
    padding: '18px',
  },
  userHeader: {
    alignItems: 'center',
    borderBottom: '1px solid #e2e8f0',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '16px',
    justifyContent: 'space-between',
    paddingBottom: '16px',
  },
};

export const deleteOutlineBtnStyle: CSSProperties = {
  ...styles.actionBtn,
  borderColor: '#fecaca',
  color: '#dc2626',
};
